### ISSUE TITLE
Why is TensorProductToInternalHomAdjunctionMapWithGivenInternalHom missing?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1042]
Is there a reason why
* `TensorProductToInternalHomAdjunctionMapWithGivenInternalHom` or `InternalHomToTensorProductAdjunctionMapWithGivenRange`
* `InternalHomToTensorProductAdjunctionMapWithGivenTensorProduct` or `InternalHomToTensorProductAdjunctionMapWithGivenSource`

are missing?

**Comment by zickgraf** [comment]
I do not see a technical reason.

**Comment by mohamed-barakat** [comment]
@TKuh: Thanks for offering to add them :)
