### ISSUE TITLE
Duplicated files in archive?

### ISSUE THREAD

**Issue by alex-konovalov** [homalg-project/CAP_project#107]
the `CAP-2017.09.09.tar.gz` archive has two files whose names only differ by uppercase/lowercase usage:

```
doc/_Chapter_Managing_Derived_Methods.xml
doc/_Chapter_Managing_derived_methods.xml
```
This causes a problem when e.g. one unpacks GAP archive for Windows:
```
+ unzip -q gap4r8p8_2017_09_21-23_09-nobin-win.zip
replace gap4r8/pkg/CAP-2017.09.09/doc/_Chapter_Managing_derived_methods.xml? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```
because it is case-insensitive. Could you please fix this?

**Comment by sebasguts** [comment]
@sebastianpos This is due to the fact that we write `Managing Derived Methods` in some places, `Managing derived methods` in other places. Which spelling would you prefer?

**Comment by sebastianpos** [comment]
To be consistent with the other titles in our documentation
I would prefer `Managing Derived Methods`
