### ISSUE TITLE
Make Abelian categories constructively finite (co)complete

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1076]
The currently missing constructive finite (co)completeness of Abelian categories is due to the lack of derivations for `Equalizer*`/`Coequalizer*` in Abelian categories. Fabian suggested the following:

* Use part of the existing code for deriving `FiberProduct*`/`Pushout*` to derive `Equalizer*`/`Coequalizer*` from `DirectSumDiagonalDifference`/`DirectSumCodiagonalDifference`.
* Use the new derivations to simplify the derivations of `FiberProduct*`/`Pushout*`.

**Comment by zickgraf** [comment]
>     * Use the new derivations to simplify the derivations of `FiberProduct*`/`Pushout*`.

ProjectionInFactorOfFiberProduct is already derived from equalizers and direct products: https://github.com/homalg-project/CAP_project/blob/99154c4d02ef76b9667caf6df3d314f0b92b7748/CAP/gap/DerivedMethods.gi#L286-L301

**Comment by TKuh** [comment]
> Use part of the existing code for deriving `FiberProduct*`/`Pushout*` to derive `Equalizer*`/`Coequalizer*` from `DirectSumDiagonalDifference`/`DirectSumCodiagonalDifference`.

I don't think it's that easy. :/ 

Roughly, what `DirectSumDiagonalDifference` does, is to construct a matrix

$\text{DiagMat}(\beta_1 - \beta_2, \beta_2 - \beta_3, ..., \beta_{n-1} - \beta_n)$

which is constructed as a morphism $\delta \colon \oplus_{i=1}^{n} P_i \rightarrow \oplus_{i=1}^{n-1} B$.

Taking the kernel and composing it with the projection $\pi_j \colon \oplus_{i=1}^{n} P_i \rightarrow P_j$ gives the equations

$\mathrm{KernelEmbedding(\delta)} \cdot  \pi_i \cdot \beta_i = \mathrm{KernelEmbedding(\delta)} \cdot  \pi_j \cdot \beta_j$

For a detailed understanding, one really has to look at the code. [Here](https://github.com/TKuh/CAP_project/blob/equalizer_via_diagonal_diff/CAP/examples/equalizer_via_diagonal_diff.g) is an example of what happens, when one implements equalizers via `DirectSumDiagonalDifference`.

I think `DirectSumDiagonalDifference` is tailor-made to work with fiber products, but it does not work with equalizers. `EmbeddingOfEqualizer` should return a single morphism working for all the $\beta_i$'s. But here we obtain the morphisms $\mathrm{KernelEmbedding(\delta)} \cdot  \pi_i$ which are "equalizing" the $\beta_i$'s.

One way to actually compute equalizers is to iterate kernels: 
$f_1,f_2,f_3 : A \rightarrow B, \quad \epsilon_1 = \text{Ker}(f_1-f_2), \quad \epsilon_2 = \text{Ker}(\epsilon_1 \cdot f_2 - \epsilon_1 \cdot f_3)$. 
Then $\epsilon_2 \cdot \epsilon_1$ equalizes $f_1,f_2,f_3$.

**Comment by zickgraf** [comment]
Are you sure about the `DiagMat`? I think its a `UniversalMorphismIntoDirectProduct` = `UnionOfColums`. And the $\beta_i$ in the `DiagMat` should be prepended by the projections, right?

But yes, the instructions above are misleading. This should read:
* Introduce an analogon of `DirectSumDiagonalDifference` for equalizers: this is just the degenerate case $(\beta_1 - \beta_2, \beta_2 - \beta_3, \dots)$.
* Derive the equalizer as the kernel of this (this gives the iterated kernel you mentioned in a single step).
* Derive DirectSumDiagonalDifference from this.
* Check using CompilerForCAP that the derivation of FiberProduct -> DirectSumDiagonalDifference -> Equalizer gives the same as the existing derivation FiberProduct -> Equalizer and drop the latter.

**Comment by mohamed-barakat** [comment]
Fabian was faster :)

**Comment by TKuh** [comment]
Wow, thank you for your fast reply!

> Are you sure about the `DiagMat`? I think its a `UniversalMorphismIntoDirectProduct` = `UnionOfColums`. 

 Ah, I had that wrong in my mind. Sorry.

> And the βi in the `DiagMat` should be prepended by the projections, right?

Yes, here my 'rough' explanation was too rough. :)

> 
> But yes, the instructions above are misleading. This should read:
> 
>     * Introduce an analogon of `DirectSumDiagonalDifference` for equalizers: this is just the degenerate case (β1−β2,β2−β3,…).
> 
>     * Derive the equalizer as the kernel of this (this gives the iterated kernel you mentioned in a single step).

Ok, I don't understand (yet) how to do this mathematically. But I can talk about this with Mohamed tomorrow (which is in person easier anyway). Thanks a lot for that detailed explanation!

**Comment by zickgraf** [comment]
Another thing: Do we really need "DirectSum" in all those derivations? I think "DirectProduct" should suffice, and would make this derivations also trigger in a pre-additive but not additive context.

**Comment by zickgraf** [comment]
Fixed by PRs related to #1124.
