### ISSUE TITLE
WARNING: Could not detect domain of function in call of NTuple. Please write a bug report including this message.

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1181]
I enforced an error to see the code he is complaining about (in the branch `functional` of `FunctorCategories`)

```gap
brk> Display( ENHANCED_SYNTAX_TREE_CODE( tree ) );
The syntax tree is not of type EXPR_FUNC. It will be wrapped in a dummy function for debugging purposes.
function (  )
    return NTuple( 2, function ( objB_2 )
            return CreateCapCategoryObjectWithAttributes( Range( FVAR_outside_of_function_stack_cat ), Length, 0 );
        end, function ( new_source_2, morB_2, new_range_2 )
            return CreateCapCategoryMorphismWithAttributes( Range( FVAR_outside_of_function_stack_cat ), new_source_2, new_range_2, AsList, [  ] );
        end );
end
```

**Comment by zickgraf** [comment]
Just to make sure: Is this still relevant after all the changes over the weekend, i.e. are you still wrapping functions in tuples?

**Comment by mohamed-barakat** [comment]
As discussed today, we can leave this open or occasionally change/replace it to/by an issue to implement `function_by_typed_domain`.

**Comment by zickgraf** [comment]
> As discussed today, we can leave this open or occasionally change/replace it to/by an issue to implement `function_by_typed_domain`.

Replaced by https://github.com/homalg-project/CAP_project/issues/1213.
