### ISSUE TITLE
EvalStringStrict

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1182]
The use of `EvalStringStrict` in `CompilerForCAP/gap/LogicTemplates.gi` produces undetected errors in the [CI of `Algebroids`](https://pipelines.actions.githubusercontent.com/serviceHosts/4ad8599e-698e-4727-b1ac-2e46bd385cc0/_apis/pipelines/1/runs/1504/signedlogcontent/3?urlExpires=2022-12-04T19%3A17%3A50.1043806Z&urlSigningMethod=HMACV1&urlSignature=Tcf8%2FY1nwI1fKWPXMe8qDuSG5dCr%2FhSHnXuzJOM2zfY%3D).

**Comment by zickgraf** [comment]
Fixed by https://github.com/homalg-project/CAP_project/pull/1184
