### ISSUE TITLE
`with_given_object_name` missing in method entry record for `*FunctorialWithGiven*`

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1246]
This is needed in AttributeCategory to be able to exclude the installation of all `*WithGiven*` if the corresponding object-part is missing.

**Comment by zickgraf** [comment]
`with_given_object_name` is not defined if `with_given_object_position = "both"` because different objects might be given. That's why it is not set for the functorials.

**Comment by zickgraf** [comment]
@mohamed-barakat Your issue here is fixed by https://github.com/homalg-project/CAP_project/pull/1247, correct?

**Comment by mohamed-barakat** [comment]
I believe yes, but I do not remember the details :)
