### ISSUE TITLE
Install convenience for ModelingObject/Morphism

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1266]

**Comment by zickgraf** [comment]
This would be technically possible, but semantically the first argument of `ModelingObject` is more than just the category of the second argument: It is the wrapper category which gives meaning to the words "modeling" and "modeled" in the first place. (Which is also the reason why a similar convenience cannot exist for `ModeledObject`).

If you would like this convenience for debugging purposes, we can add it with a warning similar to the one in `CanCompute`:
```
gap> LoadPackage( "CAP", false );; CanCompute( CapCat, IdentityMorphism );;
WARNING: calling `CanCompute` with a CAP operation as the second argument should only be done for debugging purposes.
```

If you would like this convenience for "production" code, I would strongly advise against that.

**Comment by mohamed-barakat** [comment]
Never for production code, just for convenience during debugging.

**Comment by mohamed-barakat** [comment]
I am also happy with the warning.

**Comment by mohamed-barakat** [comment]
I had to add this manually to a private branch of my `CategoryConstructor` since I keep using this in experiments.

**Comment by zickgraf** [comment]
Why don't you create a CAP PR with your additions?

**Comment by mohamed-barakat** [comment]
> Why don't you create a CAP PR with your additions?

Done. We can discuss the details tomorrow.
