### ISSUE TITLE
Deprecate and remove AddObjectRepresentation and AddMorphismRepresentation

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#1269]
This would also allow to get rid of some workarounds in `ObjectifyObjectForCAPWithAttributes`, `CreateCapCategoryObjectWithAttributes`, etc.

**Comment by zickgraf** [comment]
Are any known users of `AddObjectRepresentation` or `AddMorphismRepresentation` left?

**Comment by mohamed-barakat** [comment]
> Are any known users of `AddObjectRepresentation` or `AddMorphismRepresentation` left?

Neither in `CategoricalTowers` nor in `HigherHomologicalAlgebra`.

**Comment by zickgraf** [comment]
@TKuh Is there anything left that you are aware of? If not, I will deprecate this :-)

**Comment by TKuh** [comment]
Should be only the manual left, but we are already working on it in #1372. :+1:
