### ISSUE TITLE
Deprecate and remove ObjectifyObjectForCAPWithAttributes and ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#1270]

**Comment by TKuh** [comment]
How should one replace this call to `ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes`:

https://github.com/homalg-project/CAP_project/blob/fe3ddc77c3762e0eb90de8b0de960870410b687e/CAP/gap/CategoriesCategory.gi#L95-L119

The problem for me is how to handle the additional entries of the record `functor`.

**Comment by TKuh** [comment]
I think there are no parts left, or can you spot any @zickgraf?

**Comment by zickgraf** [comment]
> I think there are no parts left, or can you spot any @zickgraf?

What about `CategoricalTowers/IntrinsicCategories/gap/IntrinsicCategories.gi`?

**Comment by TKuh** [comment]
I deliberately left it out: https://github.com/homalg-project/CategoricalTowers/pull/286#discussion_r1258484491

**Comment by mohamed-barakat** [comment]
> I deliberately left it out: [homalg-project/CategoricalTowers#286 (comment)](https://github.com/homalg-project/CategoricalTowers/pull/286#discussion_r1258484491)

Sorry, a left over, will take care of it today.

**Comment by mohamed-barakat** [comment]
A simple replacement does not work:

* `CreateCapCategory*WithAttributes` creates a GAP object with no further components apart from the attributes in its arguments.
* Intrinsic objects/morphisms include some further components different from the above-mentioned attributes.
* Immediately after an intrinsic object/morphism is created, immediate methods are triggered which need mutable components different from the above-mentioned attributes. This results in failed access to a yet missing component.

**Comment by zickgraf** [comment]
> A simple replacement does not work:

I suggest to simply use `ObjectifyWithAttributes` because this does not require special support in CAP.

**Comment by mohamed-barakat** [comment]
> I suggest to simply use `ObjectifyWithAttributes` because this does not require special support in CAP.

But this would more or less mean replicating the code of [`ObjectifyWithAttributes`](https://github.com/homalg-project/CAP_project/blob/fde26e349dbf3ba4cefff459f9be4624fcf2e2ab/CAP/gap/CategoryObjects.gi#L275-L297), right?
