### ISSUE TITLE
BraidingInverseWithGivenTensorProducts has wrong dual_preprocessor_func

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#1295]
Steps to reproduce:
```
LoadPackage( "FreydCategoriesForCAP" );
LoadPackage( "LazyCategories" );

QQ := HomalgFieldOfRationals();

cat := CategoryOfRows( QQ : no_precompiled_code );

lazy := LazyCategory( cat : only_primitive_operations );

op := Opposite( lazy : only_primitive_operations );

obj1 := ObjectConstructor( cat, 1 ) / lazy;
obj2 := ObjectConstructor( cat, 2 ) / lazy;

op_obj1 := ObjectConstructor( op, obj1 );
op_obj2 := ObjectConstructor( op, obj2 );

Assert( 0, IsWellDefinedForObjects( op_obj1 ) );
Assert( 0, IsWellDefinedForObjects( op_obj2 ) );

mor := BraidingInverse( op_obj1, op_obj2 );
```
throws an error.

@TKuh Could you look at the preprocessor functions for MonoidalCategories and CartesianCategories (mostly added in https://github.com/homalg-project/CAP_project/pull/773) again and maybe enhance the test suite to catch errors like the one above? Using `dual_with_given_objects_reversed` (see the method record entry of `TensorProductOnMorphismsWithGivenTensorProducts`) could be used instead of some of the preprocessor funcs.

**Comment by TKuh** [comment]
Thank you for the hint about `dual_with_given_objects_reversed`, that's useful. 

I'm wondering about the best approach to improve the tests. I guess there's no way around `LazyCategories` to be really sure, right?

- If I use `LazyCategories` directly in the test methods (e.g. [here](https://github.com/homalg-project/CAP_project/blob/master/MonoidalCategories/gap/BraidedMonoidalCategoriesTest.gi)), then `MonoidalCategories` depends on `LazyCategories` ...
- Moving the tests to `LazyCategories` and enhance them there would be fine, but I think they should stay closer to `MonoidalCategories`.
- Last option: introduce new tests similar to your code above directly in `LazyCategories`.

Any other ideas? If not, the last point seems the cleanest to me.

**Comment by zickgraf** [comment]
Thanks for the quick response and PR!

Yes, I currently see no way around using `LazyCategories` and I agree that those tests should happen there to avoid additional dependencies. There are already tests which I assume should catch this:
https://github.com/homalg-project/CategoricalTowers/blob/b4fea027df9e3973265fdd6725aa9c8439b9a878/LazyCategories/tst/TerminalCategoryMonoidal.tst#L74-L93
Can you investigate why those tests do not catch the error in this issue?

**Comment by TKuh** [comment]
The above error can be caught via the tests:

```gap
gap> LoadPackage("LazyCategories", false);;
gap> T := TerminalCategoryWithMultipleObjects();;
gap> L := LazyCategory( T : primitive_operations := true );;
gap> a := "a" / T / L;;
gap> b := "b" / T / L;;
gap> 
gap> BraidedMonoidalCategoriesTest( L, a, b : only_primitive_operations := true );;
```

**Comment by zickgraf** [comment]
> However, the option in this second call does not have an effect on the created opposite category:
>
> An obvious fix is to split the calls with only_primitive_operations := true into a separate test file.

`Opposite` is an attribute, that's why the option does not change the result when a category without the option was already created. We have already discovered this problem but it was somehow lost again: https://github.com/homalg-project/CAP_project/issues/886#issuecomment-1125757335 Splitting the example into a separate test file will not help because `make test` runs all test files in the same session. You can use `Opposite` with two arguments (the second being the name of the opposite category) to avoid calling the attribute. Please create a separate PR so we can check that the CI for LazyCategories actually fails without #1297.

**Comment by TKuh** [comment]
Thank you very much, also for pointing out the version of `Opposite` with two arguments!

Now, this leads me to the following similar problem with objects:

```gap
gap> LoadPackage("LazyCategories", false);;
gap> T := TerminalCategoryWithMultipleObjects();;
gap> L := LazyCategory( T : primitive_operations := true );;
gap> a := "a" / T / L;;
gap> 
gap> op := Opposite( L, "op" );;
gap> op_primitive := Opposite( L, "op" : only_primitive_operations := true );;
gap> 
gap> ObjectConstructor( op, a );
<An object in op>
gap> 
gap> ObjectConstructor( op_primitive, a );
Error, the result of the function ObjectConstructor of the category named op does not lie in the expected filter <Category "opInstanceObjectFilter">. You can access the value via the local variable 'value' in a break loop. at /home/tom/.gap/pkg/CAP_project/CAP/gap/ToolsForCategories.gi:400 called from
output_sanity_check_function( result ); at /home/tom/.gap/pkg/CAP_project/CAP/gap/InstallAdds.gi:477 called from
CallFuncList( func, arg ) at /home/tom/.gap/pkg/homalg_project/ToolsForHomalg/gap/CachingObjects.gi:767 called from
<function "ObjectConstructor method">( <arguments> )
 called from read-eval loop at *stdin*:12
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```
I'm reusing various variables in the tests, so it would be very helpful, if there was a way around this. I could create new variables for every call to `Opposite`, but this would blow up the test files.

(Sorry for asking if this has an obvious solution. I tried various things to trick the opposite mechanism, but I couldn't figure out a way).

**Comment by zickgraf** [comment]
> Now, this leads me to the following similar problem with objects:

Ah, sorry, I was not aware of this. So actually the code does not allow to work with two non-identical opposite categories of the same category :/ I will have to look at your tests and the code for opposite categories in detail to see what a good solution could be.

**Comment by zickgraf** [comment]
https://github.com/homalg-project/CAP_project/pull/1307 should fix your problems by only handling the first instance of an opposite category via attributes. The solution is a bit convoluted, but it is the easiest solution which does not break backwards compatibility.

**Comment by zickgraf** [comment]
For future reference: The asymmetry between `BraidingInverse` and `CartesianBraidingInverse` comes from the construction of the terminal category and the fact that every cartesian category is symmetric. The terminal category tries to install a minimal set of operations, so it has to install `BraidingInverseWithGiven...` but not `CartesianBraidingInverseWithGiven...` because the latter can be derived:

https://github.com/homalg-project/CAP_project/blob/6612a6d067f7084b8a7e5436abe978e50bb59322/CartesianCategories/gap/CartesianCategoriesDerivedMethods_extra.gi#L153-L167

Now for the tests: Testing with `only_primitive_operations` at level $l$ of the tower mainly tests derivations in level $l$ (horizontal connections), while testing with all operations at level $l$ mainly tests the lifting of operations from level $l - 1$ to level $l$ (vertical connections). In both cases, all levels $< l$ should be created with `(only_)primitive_operations`, otherwise there is no difference between testing with and without `only_primitive_operations` at level $l$ (except for the special case explained below). So here we always want to test with `primitive_operations := true` for LazyCategory.

So why does it throw an error without `primitive_operations := true` but not with `primitive_operations := true`? This is because LazyCategory never lifts non-WithGiven operations. So creating LazyCategory without `primitive_operations := true` actually means: Lift all operations except non-WithGivens. And then creating Opposite with `only_primitive_operations := true` means: Test all remaining derivations, which essentially are only the non-WithGiven -> WithGiven derivations. Due to these implementation details, `CartesianBraidingInverse` calls `CartesianBraidingInverseWithGiven...` and the latter is primitively installed. But in a perfect world, LazyCategory would actually lift `CartesianBraidingInverse` so this would not happen. We might actually be getting there in the future with `output_source/range_getter_string`, so this is nothing one should rely on.

So what's the correct solution? If one wants to test the vertical connection for XYZ from level $l - 1$ to level $l$ in a tower (which we want here to find errors in the pre- and postprocessors) one should:
1. Create all levels $< l$ with `(only_)primitive_operations`.
2. Create level $l$ without `(only_)primitive_operations`.
3. Call XYZ.

The last step is what is missing here: The tests only call `CartesianBraidingInverse` but not `CartesianBraidingInverseWithGiven...`. So to make one systematically catches errors like these, the tests should call every operation directly.

**Comment by TKuh** [comment]
Thank you so much! I only had a sketchy idea of what was going on, but that clarifies it. :)

How urgent are tests for the `WithGiven*` operations for you? Adding all of them roughly doubles the size of the tests, so I would add them step by step (probably in a draft), unless you would like to have them now.

**Comment by zickgraf** [comment]
> How urgent are tests for the `WithGiven*` operations for you?

For me personally, none of these tests are urgent, @mohamed-barakat has to say. What I think is important is that we are clear and consistent about what is tested and what is not. So comments like https://github.com/homalg-project/CAP_project/blob/b7303ec0f0a8ef7595374f758d83f35f94378161/MonoidalCategories/gap/AdditiveMonoidalCategoriesMethodRecord.gi#L30 should be removed if we do not explicitly test the WithGiven versions.

> Adding all of them roughly doubles the size of the tests, so I would add them step by step (probably in a draft), unless you would like to have them now.

If I would implement this, I would probably write a function `TestXAndItsWithGiven` which would get the arguments of the WithGiven-version and then tests both the WithGiven and the NonWithGiven version. Then the size of the tests would not double. Or I would try do automatically generate the test files from the method record (and maybe some additional information where required). But as long as things are consistent, I am happy with any solution!

**Comment by zickgraf** [comment]
Thanks for removing the comments! Consistency 🎉
