### ISSUE TITLE
Constructive implication vs. mathematical implication in InfoStringOfInstalledOperationsOfCategory

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#1360]
I'm a bit confused by this block:

https://github.com/homalg-project/CAP_project/blob/0db711c7441052bfa71973488d321e0e741b0b6f/CAP/gap/PrintingFunctions.gi#L25-L27

There seem to be two kinds of implications considered: "Constructive implication" (`IsSubset(...)`) and "mathematical implication" (`ListImpliedFilters`). However, constructive implication does not imply mathematical implication. This leads to an unexpected output in the following example:
```
LoadPackage( "CAP" );

DeclareProperty( "IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis", IsCapCategory );

AddCategoricalProperty( [ "IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis", "IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis" ] );

CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD.IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis := Concatenation(
    CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD.IsPreAbelianCategory,
    [
        "LiftAlongMonomorphism",
        "ColiftAlongEpimorphism",
    ]
);

InstallTrueMethod( IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis, IsAbelianCategory );


cat := DummyCategory( rec(
    list_of_operations_to_install := CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD.IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis,
    properties := [ "IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis", "IsAbelianCategory" ],
) );

Display( cat );
```

outputs

```
A CAP category with name AutomaticCapCategory1:

26 primitive operations were used to derive 182 operations for this category which algorithmically
* IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis
```

that is, `IsAbelianCategory` is not shown.

(I have not yet thought about the converse, i.e. if mathematical implication always implies constructive implication, at least in our context.)

**Comment by zickgraf** [comment]
Regarding the converse, i.e. if mathematical implication always implies constructive implication: I think in general this does not have to be true either. We could have two constructive properties A and B such that A implies B mathematically but there is no way to derive the operations of B from operations of A. But of course in our constructive context that would probably be a very uncommon situation.

**Comment by mohamed-barakat** [comment]
I assume the example is designed such that:

```gap
gap> Difference( CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD.IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis, CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD.IsAbelianCategory );
[  ]
gap> Difference( CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD.IsAbelianCategory, CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD.IsPreAbelianCategoryWithLiftsAlongMonosAndColiftsAlongEpis );
[  ]
```

Correct?

**Comment by zickgraf** [comment]
> Correct?

Yes.

#1362 now has a fix by simply not taking constructive implication into account. This fixes the above example, i.e. the case that there is a constructive implication but not a mathematical one. The converse, i.e. that we have a mathematical implication but not a constructive implication, is unnatural in our context. And if it actually occurs and the mathematically implied property is not constructive, it will be listed under the mathematical properties anyway.
