### ISSUE TITLE
Renaming DummyCategory to PlaceholderCategory

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#1378]
I'm thinking about renaming "DummyCategory" to "PlaceholderCategory" because I think the latter is more self-explanatory. @mohamed-barakat @kamalsaleh @TKuh What do you think?

**Comment by mohamed-barakat** [comment]
I have been trying to come up with a better name, but I now think `PlaceholderCategory` is good.

**Comment by zickgraf** [comment]
In my thesis, I now talk more generally about *dummy implementations*. In this context, replacing *dummy* by *placeholder* is less useful. Hence, I will also stick with `DummyCategory`.
