### ISSUE TITLE
Installation names should be CAP specific

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/CAP_project#139]
The following CAP methods have
installation names that are too generic (in the sense
that they are widely used within other packages):

- `IsZeroForMorphisms` has installation name `IsZero`
- `AdditionForMorphisms` has installation name `+`
- `SubtractionForMorphisms` has installation name `-`
- `IsZeroForObjects` has installation name `IsZero`

This causes trouble when turning GAP objects
into CAP objects/morphisms that already have
methods for `IsZero` (or `+`, `-`) which are 
then probably ranked higher than the CAP-methods.

Is it a good idea to change the installation names
to the more specific CAP names in these cases?

**Comment by sebasguts** [comment]
Depends.

I think it is not a good idea to drop the shortcuts `+`, `-`, and `IsZero` completely, since they are kind of intuitive and fit into the GAP context.

However, it would probably be a good idea to flip the ordering of how this is executed, i.e., install the methods as `IsZeroForMorphisms` etc. and then redirect `IsZero` to this method. We could then recoomend the use of the long names in code, and just leave `+`, `-`, and `IsZero` for short examples.

Are you aware of any place there this is currently a problem?

**Comment by sebastianpos** [comment]
I agree with the idea to flip the ordering of execution.
I'll preprare a pull request for that.

Yes, this problem occurs when integrating QPA morphisms
into CAP.

**Comment by sebasguts** [comment]
After thinking about this a bit more, I think my proposal (and subsequently, PR #140 ) is not really what we want to do when it comes to `IsZero`, for the following reasons:

For CAP cells that have no `IsZero` installed from somewhere else, `IsZero` is now not really a synonym for `IsZeroForObjects/Morphisms`. Specially when triggered by the logic, but also when triggered in code that use the specific name, the property `IsZero` will not get set, basically rendering this filter useless. So one should not use it anyway, as it might not work as intended.

The confusion gets even worse if one uses CAP with cells that already have an `IsZero`. Then the behaviour is kind of arbitrary, and does not fit to the rest of CAP.

I am not completely sure what to do here, it is a delicate question. Here are proposals, all with the possible counterpoints:
1. Remove `IsZero` completely for CAP cells. This makes CAP less intuitive to use, and does it make fit less seemlessly in the GAP context. Furthermore, it might break a lot of existing code. `IsZero` is used and documented in CAP for several years now.
2. Leave it as it is, and do not allow to directly use CAP (without wrappers) for objects that have `IsZero` installed. This of course adds a layer of complication for use cases, and can slow things down.
3. Use what we do, but strongly advise people to not use `IsZero` anywhere else than in the interactive shell for testing. Furthermore advice people that `HasIsZero` and `SetIsZero` will not work. This will cause a lot of complaints, as people ignore/do not read/forget manuals.

I am not sure what to do. I would prefer the first option, but it is a *HUGE* change. Note that this affects only `IsZero`, not `+` or `-`.

**Comment by sebasguts** [comment]
We chose to use 3. here. The encouraged commands are now `IsZeroForObjects` and `IsZeroForMorphisms`. The command `IsZero` should not be used.
