### ISSUE TITLE
DeductiveSystemForCAP

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#1397]
DeductiveSystemForCAP is broken since at least https://github.com/homalg-project/CAP_project/commit/2e0c5be19fdef6c0eb273c3ea5940b87c1901c7d, 8 years ago. (Creating a deductive system object or morphism calls `INSTALL_TODO_FOR_LOGICAL_THEOREMS` with three arguments which is not possible anymore since that commit.)

@sebastianpos Does it make sense to keep this code around?

**Comment by sebastianpos** [comment]
No, it does not.

You can remove it if you like to do that.
