### ISSUE TITLE
Fix documentation of MorphismFromCoimageToImageWithGivenObjects

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1475]

**Comment by mohamed-barakat** [comment]
I am also unhappy with the order of arguments in `InverseMorphismFromCoimageToImageWithGivenObjects`. It does not align with the ordering convention used by other `*WithGivenObjects` operations.

**Comment by zickgraf** [comment]
> I am also unhappy with the order of arguments in `InverseMorphismFromCoimageToImageWithGivenObjects`. It does not align with the ordering convention used by other `*WithGivenObjects` operations.

That's indeed not very nice, good catch. I think this will produce errors when introducing `InverseMorphismFromCoimageToImage` because CAP makes assertions about the order of WithGiven arguments.

**Comment by mohamed-barakat** [comment]
> That's indeed not very nice, good catch. I think this will produce errors when introducing `InverseMorphismFromCoimageToImage` because CAP makes assertions about the order of WithGiven arguments.

What do you mean by "introducing `InverseMorphismFromCoimageToImage`", the latter is already there :)
