### ISSUE TITLE
Issues with the list syntax in the documentation

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#156]
My intuitive syntax for lists is the following: A list with `n` entries can either be written as `(a_1,...,a_n)` or as `(a_i)_{i=1,...,n}`. On the contrary, the notation `(a_i,b_i)_{i=1,...,n}` does not define a list, since it has multiple possible interpretations:
* `(a_1,...,a_n,b_1,...,b_n)`
* `(a_1,b_1,a_2,b_2,...,a_n,b_n)`
* `((a_1,b_1),(a_2,b_2),...,(a_n,b_n))`

In https://github.com/homalg-project/CAP_project/blob/9f9862ca99dd1a6a89ce7c87e2c7275eb31fa89e/CAP/gap/UniversalObjects.gd#L2744 this notation is used and might cause confusion. Additionally, in https://github.com/homalg-project/CAP_project/blob/9f9862ca99dd1a6a89ce7c87e2c7275eb31fa89e/CAP/gap/UniversalObjects.gd#L2728 this notation is used and wrapped in another pair of parentheses.

In the corresponding documentation of the Pushout, the same issue occurs.

**Comment by sebastianpos** [comment]
@zickgraf Do you agree that this issue is now settled via #211?

**Comment by zickgraf** [comment]
I agree, I have grepped for other occurrences of this problem and have found none.
