### ISSUE TITLE
Drop support for installing CAP operations with additional filters

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#1651]
CAP has support for installing methods for CAP operations with additional filters, for example for speeding up the composition with identity morphisms in CategoryOfRows:
https://github.com/homalg-project/CAP_project/blob/c3a0d09a41b25da86d14bd2e19723563eadb41f8/FreydCategoriesForCAP/gap/CategoryOfRows.gi#L419-L423

I propose dropping support for this mechanism. Reasoning:

* As far as I am aware, the mechanism is only used at very few places: For categories of rows, for left/right presentations, for generalized morphisms, and for group representations.
* The mechanism is not really integrated into other concepts: For example, neither category constructors like OppositeCategory nor CompilerForCAP handle methods installed with additional filters.
* The mechanism complicates many things in InstallAdds.gi.

@sebastianpos Do you see the need to keep the mechanism?

@mohamed-barakat @kamalsaleh Do you have any code relying on this?

**Comment by mohamed-barakat** [comment]
We now have the compiler. From my side, this mechanism can be dropped.

**Comment by zickgraf** [comment]
> We now have the compiler. From my side, this mechanism can be dropped.

I agree, but just for the record: compilation is not an exact replacement for this mechanism, because the mechanism can dynamically optimize at runtime while compilation can only statically optimize at compile time.

**Comment by mohamed-barakat** [comment]
I agree. The compiler does not support this branching, so it is useless for the compiled code, but relevant during runtime if one uses the noncompiled code.
