### ISSUE TITLE
Drop support for "object/morphism_or_fail"

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#1659]
I suggest to drop the support for "object_or_fail" and "morphism_or_fail" in CAP.

Rationale: "object_or_fail" does not occur at all and "morphism_or_fail" only occurs six times across the whole codebase: `(Co)LiftOrFail`, `SolveLinearSystemInAbCategoryOrFail`, `WitnessIsomorphismInto/FromStandardConeObject`, `RelativeLift`. Still, grepping for "_or_fail" shows many places where we have special code just to handle these few cases.
Moreover, returning `fail` is not compatible with the type system of CompilerForCAP and compilation in general (because hoisting can lead to wrong code if some intermediate result is `fail`).

Solution:
* `(Co)LiftOrFail` and `SolveLinearSystemInAbCategoryOrFail` can be turned into convenience methods first checking `IsLiftable` etc.
* `WitnessIsomorphismInto/FromStandardConeObject` and `RelativeLift` can be handled by introducing `IsIsomorphicToStandardConeObject` and `IsRelativelyLiftable` (or similar), similar to the situation of `Lift` and `IsLiftable`.

@mohamed-barakat @kamalsaleh Do you agree?

**Comment by mohamed-barakat** [comment]
I agree.

**Comment by kamalsaleh** [comment]
Me too

**Comment by zickgraf** [comment]
Thanks for your fast replies!

`RelativeLift` was easy to fix because the implementations did not properly consider the `fail` case anyway, see https://github.com/homalg-project/CategoricalTowers/pull/571.

For `WitnessIsomorphismInto/FromStandardConeObject`, things are more complicated because the `fail` case is actually considered and spreads to more operations like `WitnessIsomorphismIntoStandardExactTriangle`. Additionally, I cannot find a category which actually implements `WitnessIsomorphismInto/FromStandardConeObject`, which is unexpected. @kamalsaleh Could you have a look?

**Comment by kamalsaleh** [comment]
I have created a PR https://github.com/homalg-project/HigherHomologicalAlgebra/pull/188 to avoid using `SolveLinearSystemInAbCategoryOrFail`. Could you take a look if that would be enough?

**Comment by zickgraf** [comment]
> I have created a PR [homalg-project/HigherHomologicalAlgebra#188](https://github.com/homalg-project/HigherHomologicalAlgebra/pull/188) to avoid using `SolveLinearSystemInAbCategoryOrFail`. Could you take a look if that would be enough?

Yes, that's exactly what is needed, thank you for the quick adjustment :-)

**Comment by zickgraf** [comment]
Resolved by https://github.com/homalg-project/CAP_project/pull/1664.
