### ISSUE TITLE
Some nomenclature in MonoidalCategories is broken

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#1665]
There are some files named

`MonoidalCategoriesTensorProductAndUnit...`

and some files named

`MonoidalCategoriesTensorProductOnObjectsAndUnitObject...`

which actually belong together. This is confusing and I think both names are bad. I suggest the prefix

`MonoidalCategoriesTensorProductOnObjectsAndTensorUnit...`

instead.

Cause: The file `MonoidalCategoriesTensorProductAndUnitMethodRecord.gi` was not properly renamed in https://github.com/homalg-project/CAP_project/commit/9cfb4d91bc12cba055db1713b8285be2f72025f7.

**Comment by mohamed-barakat** [comment]
I agree. I can do the renaming or merge a PR, whatever faster :)

**Comment by zickgraf** [comment]
I just noticed that `MonoidalCategoriesTensorProductAndUnit` also spreads to other packages via the function `MonoidalCategoriesTensorProductAndUnitTest`, which should also be renamed.

> I can do the renaming or merge a PR, whatever faster :)

It would be nice if you could to the renaming, I'm in the middle of a larger refactoring of the `Add...` functions  with many lose ends, so my workspace is in a quite messy state right now :D

**Comment by zickgraf** [comment]
https://github.com/homalg-project/CAP_project/pull/1666 is incomplete because it does not rename `MonoidalCategoriesTensorProductOnObjectsAndUnitObject...`
I can create a PR as part of a larger upcoming change.
