### ISSUE TITLE
Make new release for GAP 4.10

### ISSUE THREAD

**Issue by alex-konovalov** [homalg-project/CAP_project#190]
Pull request #157 was merged, but no CAP releases were published after that. Hence I still can not include latest releases of the CAP project in GAP 4.9 distribution (see https://github.com/gap-system/gap/wiki/Package-updates-status - am using their stable versions instead). I have mentioned that in #117, but that issue is closed and is off the radar, so making a new one.

**Comment by alex-konovalov** [comment]
This is long overdue, and although I have a clear mechanism to state package assembly specification in https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/Makefile, that requires extra care from me, and makes your latest release completely excluded both from automated testing and from user testing. And in addition, there should be test files!

**Comment by fingolfin** [comment]
I think part of the holdup is that the desire to simplify things for CAP and homalg via meta packages (to be discussed next week). However, that's a feature that will arrive at its earliest with GAP 4.11 (so will take *at least* half a year); it would be good to have CAP (and homalg) releases before that.

**Comment by sebasguts** [comment]
You are pretty much right. I guess I can just make a release now :).

**Comment by sebasguts** [comment]
Done
