### ISSUE TITLE
Publish new release of CAP package in time for GAP 4.10

### ISSUE THREAD

**Issue by alex-konovalov** [homalg-project/CAP_project#196]
As you can see from https://github.com/gap-system/gap/wiki/Package-updates-status, the following versions are picked up for the redistribution with GAP:

| Package name               | Latest      | Date       | Stable     | Date       | 
| --- | --- | --- | --- | --- |
CAP                        | 2017.12.30 | 30/12/2017 | 2017.09.25 | 25/09/2017 | 
GeneralizedMorphismsForCAP | 2018.06.15 | 15/06/2018 | 2017.09.09 | 09/09/2017 | 
LinearAlgebraForCAP        | 2018.02.07 | 07/02/2018 | 2017.09.09 | 09/09/2017 | 
ModulePresentationsForCAP  | 2018.02.02 | 02/02/2018 | 2017.09.09 | 09/09/2017 | 

The page http://homalg-project.github.io/CAP_project/CAP/ still serves CAP 2017.12.30, while GeneralizedMorphismsForCAP and ModulePresentationsForCAP require CAP >=2018.02.02, and LinearAlgebraForCAP - CAP >= 2018.02.07.

Therefore, CAP components' updates are not usable - please publish new version of CAP as well.

**Comment by sebasguts** [comment]
Thanks for noticing. I fixed this, although I also need to fix the release script, as the CAP website will not update again using the script.
