### ISSUE TITLE
Convenience for DirectProduct and Coproduct

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/CAP_project#219]
We provide a convenience function for `DirectSum`
with filters `[ IsList, IsCapCategory ]` that delegates to `ZeroObject`
in the case where the given list is empty.

We should have similar convenience functions for `DirectProduct`
(delegating to `TerminalObject`) and `Coproduct` (delegating to `InitialObject`).

**Comment by zickgraf** [comment]
@sebastianpos I just came across this issue and think that we can close it because we now actually allow empty (co)limits. Do you agree?

**Comment by sebastianpos** [comment]
Yes, thank you.
