### ISSUE TITLE
Should we allow objects/morphisms from other categories as input/output?

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/CAP_project#224]
I would like to introduce homomorphism structures in CAP as CAP-operations.
A homomorphism structure of a category **A** consists of a functor
**A^{op} x A -> B,**
(where **B** is not necessarily given by **A** itself) plus some other data that 
make it a useful replacement for the usual Set-valued Hom-functor.

In this issue I would like to discuss the following idea of how to use the current 
CAP system to deal with operations that have objects/morphisms from other 
categories as input/output. I will use the notion of a homomorphism structure 
as a guiding example in this issue.

One way to realize this idea is to use declarations

```
DeclareOperation( "HomomorphismStructureOnObjects",
                  [ IsCapCategoryObject, IsCapCategoryObject ] );

DeclareOperation( "HomomorphismStructureOnMorphismsWithGivenObjects",
                  [ IsCapCategoryObject, IsCapCategoryMorphism, IsCapCategoryMorphism, IsCapCategoryObject ] );

```

and the following entries in the method record:

```
HomomorphismStructureOnObjects := rec(
  installation_name := "HomomorphismStructureOnObjects",
  filter_list := [ "object", "object" ],
  return_type := "other_object",
  cache_name := "HomomorphismStructureOnObjects",
),

HomomorphismStructureOnMorphismsWithGivenObjects := rec(
  installation_name := "HomomorphismStructureOnMorphismsWithGivenObjects",
  filter_list := [ IsCapCategoryObject, "morphism", "morphism", IsCapCategoryObject ],
  return_type := "other_morphism",
  cache_name := "HomomorphismStructureOnObjects",
),
```

So the two novelties are:
1) I allow `return_type` to be `other_object` or `other_morphism`
2) I allow `IsCapCategoryObject` as an entry in `filter_list` to refer to objects that are lying 
in a category possibly different from the category **A** to which the method is assigned to.

Here are some thoughts that I had concerning this realization:
- My first concern was that it might happen that the output
object in **B** might be tried to be added to **A**. However, this is not the case. The reason is that `return_type` appears to be only relevant in the decision which Add-function is called,
and since the case `other_object`/`other_morphism` is unknown to the system, 
its Add-function is set to `ReturnTrue`

- Another question was with which function objects/morphisms in **B** will be compared
by the cache in the case that they are arguments in a function for **A**? The answer seems to be that they are still compared with `IsEqualForCache` in B, which is good.
The reason is that `IsEqualForCache` is a `ToolsForHomalg` method, and
a particular instance of `IsEqualForCacheForObjects`/`IsEqualForCacheForMorphisms` installs `IsEqualForCache` with the filters for the particular objects/morphisms in the category.

The biggest downside so far is that there is no way in the current
CAP system to specify the filter of the arguments in **B** better than
by `IsCapCategoryObject`.
However, I don't think this is too bad since a call like
`HomomorphismStructureOnMorphismsWithGivenObjects(Hom_Object_1, alpha, beta, Hom_Object_2)`
is uniquely determined by the category **A** in which alpha and beta reside,
since, as always, we would allow only a single homomorphism structure per category.

Can you think of other complications that might come up and that I haven't thought about?

I would really like to be able to implement homomorphism structures.

**Comment by sebasguts** [comment]
I think you basically described the problems on point.

The `IsEqualForCache` has a fallback to `IsIdenticalObj`, so nothing to fear here.

We could actually hack something together by giving an optional entry `add_to_category_from_argument`, which could determine an argument from which the category the output is to be added from. Might be potentially dangerous if abused, but okay.

ATM I do not see any potential drawbacks of this solution. I could even give you input keywords like `other_object` which can default to `IsCapCategoryObject`. We could also allow list of categories as input for the adds, and then use a syntax like `morphism[2]` to say that something has to be in category two. Same for output if you want.

All of the above is easy. Note that it would be still hard to actually add this method to the method graph of both categories.

Would you like to have those input lists?

**Comment by sebastianpos** [comment]
I would be happy with something like `add_to_category_from_argument`.

Furthermore, to be more specific than `IsCapCategoryObject` in the method record
would also be nice, by using keywords like `other_object[2]` meaning something like
_an object from the second additional category_.

Do you see a solution for the problem that the concrete filter
for the "other objects/morphisms" cannot be set at the moment?

Yes, derivations are hard to handle.
At the moment, I would treat a CAP-operation like
`HomomorphismStructureOnMorphismsWithGivenObjects`
as follows:
1) such a CAP-operation "belongs" to the category **A** for which it was
added (via `AddHomomorphismStructureOnMorphismsWithGivenObjects( A, ... )` )
2) in particular, this CAP-operation belongs to the method graph of **A**
3) if you write a derivation for it, you have to be sure that all operations in this derivation
that are not operations in **A** but in **B** can actually be performed within **B**

I think for 3) one would have to ensure somehow that the automatic counting
of basic operations in a derivation is deactivated. Do you know if this would be
possible at the moment?

**Comment by zickgraf** [comment]
Adding objects/morphisms from other categories as input/output has now been possible for a long time, and specifying the other category correctly in (final) derivations is possible since f53276d7fdae4e0bc65e6dca4d0ef396a0ed4f88 and c5ff6260c9dcafe818e4818a39dcdbfe3a729adf.
