### ISSUE TITLE
IsStrictMonoidalCategory is falsely set as true for categories of module presentations

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#234]
`SetIsStrictMonoidalCategory(category, true)` is wrong in
* `LeftPresentations`
* `RightPresentations`
* `GradedLeftPresentations`
* `GradedRightPresentations`
```
gap> LoadPackage( "modulepresentation" );
gap> ZZ := HomalgRingOfIntegers();;
gap> M := AsLeftPresentation( HomalgMatrix( "[ 2, 3 ]", 1, 2, ZZ ) );;
gap> L := TensorProduct( TensorProduct( M, M ), M );;
gap> R := TensorProduct( M, TensorProduct( M, M ) );;
gap> IsEqualForObjects( L, R );
false
gap> Display( L );
[ [  2,  3,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  2,  3,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  2,  3,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  2,  3 ],
  [  2,  0,  3,  0,  0,  0,  0,  0 ],
  [  0,  2,  0,  3,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  2,  0,  3,  0 ],
  [  0,  0,  0,  0,  0,  2,  0,  3 ],
  [  2,  0,  0,  0,  3,  0,  0,  0 ],
  [  0,  2,  0,  0,  0,  3,  0,  0 ],
  [  0,  0,  2,  0,  0,  0,  3,  0 ],
  [  0,  0,  0,  2,  0,  0,  0,  3 ] ]

An object in Category of left presentations of Z
gap> Display( R );
[ [  2,  3,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  2,  3,  0,  0,  0,  0 ],
  [  2,  0,  3,  0,  0,  0,  0,  0 ],
  [  0,  2,  0,  3,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  2,  3,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  2,  3 ],
  [  0,  0,  0,  0,  2,  0,  3,  0 ],
  [  0,  0,  0,  0,  0,  2,  0,  3 ],
  [  2,  0,  0,  0,  3,  0,  0,  0 ],
  [  0,  2,  0,  0,  0,  3,  0,  0 ],
  [  0,  0,  2,  0,  0,  0,  3,  0 ],
  [  0,  0,  0,  2,  0,  0,  0,  3 ] ]

An object in Category of left presentations of Z
```

Removing the corresponding `SetIsStrictMonoidalCategory(category, true)` prevents (wrong) derivations (e.g., for `LambdaElimination`) and breaks the testsuite.

Note: `KroneckerMat` is associative, but still, the implemented `TensorProduct` is not.

For this reason `SetIsStrictMonoidalCategory(category, true)` is probably correct in
`CAP_project/ModulePresentationsForCAP/examples/example.g`.
Since the file does not currently work I cannot test it.

**Comment by sebastianpos** [comment]
Thanks for pointing this out.
The mistake is that the associators are given by identity matrices between their source and range, but nevertheless are not themselves identity morphisms, since source and range can differ as objects.
The solution is to manually install `AssociatorLeftToRightWithGivenTensorProducts` or `AssociatorRightToLeftWithGivenTensorProducts` by constructing presentation morphisms whose underlying matrix is the identity matrix.
I can do this as soon as I find time.
