### ISSUE TITLE
Rename CoevaluationForDual -> CoevaluationForDualizable

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#235]
I suggest renaming `CoevaluationForDual` -> `CoevaluationForDualizable` or `CoevaluationForDualizableObject`; see https://ncatlab.org/nlab/show/coevaluation+map.

In a cartesian closed category (e.g. Sets) only the terminal object is dualizable.

**Comment by sebastianpos** [comment]
In CAP, we have the following notion of a dual: given an object `A` in a monoidal closed category, its dual is an object which is isomorphic to `InternalHom( A, 1 )`. This notion of a dual is weaker than the one suggested in nlab. The reason why we chose this weaker notion is to be able to call `Hom( M, R )` the dual module for `M` in the context of R-modules over a commutative ring R. Do you suggest to introduce the nlab version of a dual to CAP as an additional notion and call it a `dualizable object`?

**Comment by mohamed-barakat** [comment]
I will summarize what I kept from our phone call today:

* CAP operations are total by default, and what I am suggesting would
  - make the operation partial
  - and would even change the specification
* we agreed on my suggestion on moving the three CAP operations `CoevaluationForDual`, `TraceMap`, and `RankMorphism` to the rigid symmetric closed monoidal section of the declarations.
