### ISSUE TITLE
Bug in adding some methods in opposite categories

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/CAP_project#244]
Suppose that `UniversalMorphismFromImage` can be computed in a category **C**, and `alpha, u` and `v` are morphisms in the **C** such that `alpha = PreCompose( u, v) `and v a monomophism then:

`UniversalMorphismIntoCoimage( alpha^op, [ v^op, u^op ] ) = UniversalMorphismFromImage( alpha, [ u, v ] )^op.`

But what CAP tries to do is to compute: `UniversalMorphismFromImage( alpha, [ v, u ] )^op` which leads to a not well-defined input, and hence to an error caused by the `pre_function` of `UniversalMorphismFromImage`.

```
LoadPackage( "LinearAlgebra" );
Q := HomalgFieldOfRationals( );
U := VectorSpaceObject( 1, Q );
V := VectorSpaceObject( 2, Q );
f := VectorSpaceMorphism( U, HomalgMatrix( [ [ 1, 2 ] ], Q ), V );
v := ImageEmbedding( f );
u := KernelLift( CokernelProjection( f ), f );
IsEqualForMorphisms( f, PreCompose( u, v ) );
UniversalMorphismFromImage( f , [ u, v ] );
f_op := Opposite( f );
u_op := Opposite( u );
v_op := Opposite( v );
IsEqualForMorphisms( f_op, PreCompose( v_op, u_op ) );
UniversalMorphismIntoCoimage( f_op, [ v_op, u_op ] );
Error, in function UniversalMorphismFromImageWithGivenImageObject
       of category Category of matrices over Q:
       range of morphism and test factorization are not equal
```
I locally resolved the bug by touching the method record to include the information that I want in specific methods (for example: UniversalMorphismFromImage) to reverse _only_ lists in the dual_arguments and then taking this in to consideration while adding the methods in the opposite category.

You can see the locally changes -and how I encountered the bug- in the last two temporarily commits in this branch:
https://github.com/kamalsaleh/CAP_project/commits/Intersection_in_Free_Abelian_Categories

If you think this solution is feasible I can include it in the still open Pullrequest ;) .

**Comment by sebasguts** [comment]
I think the solution is good, yes, and you could submit the fix.

One minor thing about the fix: The function `list_operation_func` should not be created inside the `if` or the `for` where it is now, as this will cause a new instance of this function created for every dual operation. It would be better to create it at the beginning of the function `CAP_INTERNAL_INSTALL_OPPOSITE_ADDS_FROM_CATEGORY`, just as `create_func` and so on itself are created. In your implementation, each dual operation that uses it gets a new instance of this function, whereas in the way I propose it the function only gets created once.

**Comment by kamalsaleh** [comment]
You are right. I have changed the position of the function and included the updated fix in this commit:
https://github.com/kamalsaleh/CAP_project/commit/3295423c877a7ba29d10ea9fc554545f06f116ac
which is now part of the pull-request:
https://github.com/homalg-project/CAP_project/pull/239
