### ISSUE TITLE
MakeTest fails - variable must have a value

### ISSUE THREAD

**Issue by HereAround** [homalg-project/CAP_project#247]
I pulled from https://github.com/homalg-project/CAP_project/ and am using the latest commit
e70447dad966b6634fd4e19340bcf12a8ca36b12 on gap 4.10.0.

gap makedoc.g completes without errors, but the following gap maketest.g runs into the following error:

Error, Variable: 'CAP_INTERNAL_CAN_COMPUTE_FILTER_LIST' must have a value

This seems to be triggered in "Bialgebroids/gap/Bialgebroids.gd:62".

I can also trigger this error by starting up gap and then loading the package "Bialgebroids" via

"LoadPackage( "Bialgebroids" );"

**Comment by sebasguts** [comment]
@mohamed-barakat I thought I fixed something about it. Is this function really still needed

**Comment by zickgraf** [comment]
I can reproduce this in the package `FreydCategoriesForCAP`. This should be fixed on the current master branch of `Bialgebroids`, see https://github.com/homalg-project/Bialgebroids/commit/bff62ba95c343f4936a8683d1d0629341410d484.

**Comment by sebastianpos** [comment]
I will update the dependency of `FreydCategoriesForCAP` on the package `Bialgebroids` as soon as the version number of `Bialgebroids` will be increased.

**Comment by mohamed-barakat** [comment]
I merged Florian bump-version-PR for `Bialgebroids`.
