### ISSUE TITLE
Data structures for complexes

### ISSUE THREAD

**Issue by sebasguts** [homalg-project/CAP_project#25]
<a href="https://github.com/sebasguts"><img src="https://avatars.githubusercontent.com/u/1068084?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sebasguts](https://github.com/sebasguts)**
_Monday Mar 30, 2015 at 10:15 GMT_
_Originally opened as https://github.com/sebasguts/CAP/issues/25_

---

There should be two more data structures for complexes.
## A recursive datastructure:

 One should put in some differentials `delta_1,...,delta_n` anda function creating `delta_i` from `delta_i-j,...delta_i-1`. This could be useful, e.g., for resolutions. The recursion then can be done iteratively to not get into any depth trap. Also, caching should be crisp, for not having holes in the list of computed objects. There should also be the possibility to specify how to cleanup the cache. Maybe if one object is deleted, all objects after this object according to the function should be deleted, too.
## An extended finite complex:

Some complexes of the type

```
( C -> ... -> C )^* -> C -> ... -> C -> ( C -> ... -> C )^*
```

with some periodic part at the beginning and the end, and some finite part in the middle. This would lead to a data structure where we have complete knowledge about the complex.

**Comment by zickgraf** [comment]
The commit closing this issue (bcf382c90f19816242b8ec355ed40c8d26cb8a8e) comes from the import of existing code as `CartesianCategories` and has nothing to do with this issue -> reopen.
