### ISSUE TITLE
Primitives that take a single category as input

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/CAP_project#252]
The handling of primitives with 1 argument in the filter `IsCapCategory` is inconsistent.

For example, the (non-glueing) Add method of `TerminalObject` is overwritten in order to allow adding a 0-ary function, whereas this is not the case for `TerminalObjectFunctorial.`

**Comment by zickgraf** [comment]
If `category_as_first_argument` is set to true (the future default), the category is now always required.
