### ISSUE TITLE
Tests for FreydCategoriesForCAP

### ISSUE THREAD

**Issue by HereAround** [homalg-project/CAP_project#259]
I am using ce7a45106576ebf4202b284d589ecd07c125a5c4. Currently, the following tests for FreydCategoriesForCAP fail (for me) and thus require attention:

# Running list 1 . . .
########> Diff in                   
[ 
  "/home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CAP_p\
roject/FreydCategoriesForCAP/doc/_Chapter_Examples_and_Tests.xml", 
  549, 565 ]
# Input is:
Acat := AdditiveClosure( Aoid );;
# Expected output:
# But found:
Error, Variable: 'range_category' must have an assigned value
########
########> Diff in 
[ 
  "/home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CAP_p\
roject/FreydCategoriesForCAP/doc/_Chapter_Examples_and_Tests.xml", 
  549, 565 ]
# Input is:
a := AsAdditiveClosureMorphism( mm[1] );;
# Expected output:
# But found:
Error, Variable: 'range_category' must have an assigned value
########
########> Diff in 
[ 
  "/home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CAP_p\
roject/FreydCategoriesForCAP/doc/_Chapter_Examples_and_Tests.xml", 
  549, 565 ]
# Input is:
b := AsAdditiveClosureMorphism( mm[2] );;
# Expected output:
# But found:
Error, Variable: 'range_category' must have an assigned value
########
########> Diff in 
[ 
  "/home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CAP_p\
roject/FreydCategoriesForCAP/doc/_Chapter_Examples_and_Tests.xml", 
  549, 565 ]
# Input is:
a := AsAdelmanCategoryMorphism( a );;
# Expected output:
# But found:
Error, The given category should be able to compute Lift
########
########> Diff in 
[ 
  "/home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CAP_p\
roject/FreydCategoriesForCAP/doc/_Chapter_Examples_and_Tests.xml", 
  549, 565 ]
# Input is:
b := AsAdelmanCategoryMorphism( b );;
# Expected output:
# But found:
Error, The given category should be able to compute Lift
########
########> Diff in 
[ 
  "/home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CAP_p\
roject/FreydCategoriesForCAP/doc/_Chapter_Examples_and_Tests.xml", 
  549, 565 ]
# Input is:
pi1 := ProjectionInFactorOfFiberProduct( [ a, b ], 1 );;
# Expected output:
# But found:
Error, in function ProjectionInFactorOfFiberProduct
       of category Opposite of Freyd( Opposite of Freyd( Additive \
closure( Algebroid generated by the right quiver Q(6)[a:1->2,b:2->3,c:\
3->4] ) ) ):
       the given morphisms of the fiber product diagram must have \
equal ranges

########
########> Diff in 
[ 
  "/home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CAP_p\
roject/FreydCategoriesForCAP/doc/_Chapter_Examples_and_Tests.xml", 
  549, 565 ]
# Input is:
pi2 := ProjectionInFactorOfFiberProduct( [ a, b ], 1 );;
# Expected output:
# But found:
Error, in function ProjectionInFactorOfFiberProduct
       of category Opposite of Freyd( Opposite of Freyd( Additive \
closure( Algebroid generated by the right quiver Q(6)[a:1->2,b:2->3,c:\
3->4] ) ) ):
       the given morphisms of the fiber product diagram must have \
equal ranges

########
########> Diff in 
[ 
  "/home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CAP_p\
roject/FreydCategoriesForCAP/doc/_Chapter_Examples_and_Tests.xml", 
  549, 565 ]
# Input is:
c := CokernelColift( pi1, PreCompose( a, CokernelProjection( b ) ) );;
# Expected output:
# But found:
Error, in function PreCompose
       of category Opposite of Freyd( Opposite of Freyd( Additive \
closure( Algebroid generated by the right quiver Q(6)[a:1->2,b:2->3,c:\
3->4] ) ) ):
       morphisms not composable

########
########> Diff in 
[ 
  "/home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CAP_p\
roject/FreydCategoriesForCAP/doc/_Chapter_Examples_and_Tests.xml", 
  549, 565 ]
# Input is:
IsMonomorphism( c );
# Expected output:
true
# But found:
false
########

**Comment by zickgraf** [comment]
I can reproduce this with the following package commits:

Bialgebroids: bd9e5220d4af7f01fee7c84e066477a5926862e2
CAP_project: ce7a45106576ebf4202b284d589ecd07c125a5c4
ComplexesForCAP: 499c1155baa673efea1457463e3b3b33aad5cdc8
homalg_project: e2f8e9f123a99267f3a88867ab28a813445d966d
InfiniteLists: cbdf1f3d0b205fef34fab378602ec713f9def45c
QPA2: e846e09758155c6a4ee49b1bbd0873f68fef7c23

**Comment by sebastianpos** [comment]
Due to the merge of
homalg-project/Bialgebroids#29,
you can use the latest 
QPA2 : 3fde791f8e59ecda2009175fb398466c232fa371

With these settings, the tests work fine. However, this bug has shown me that I also had another bug in `FreydCategoriesForCAP` which was fixed in #260

**Comment by HereAround** [comment]
I confirm that with the following versions, the tests function:
Bialgebroids: 86fa551b959128a4d17a4eeb0904983285d95ed5
CAP_project: 7d1ee9583ba7ffaf92a8c41388c64c8d6caa0f15
ComplexesForCAP: 499c1155baa673efea1457463e3b3b33aad5cdc8
homalg_project: 43ae4ef936be4f05a66774446b7bfdeacaf44a6d
InfiniteLists: 511ab707253312b2f626012617b3bbffe5490c00
QPA2: 3fde791f8e59ecda2009175fb398466c232fa371
