### ISSUE TITLE
Convention for the grading in GradedRows and GradedColumns

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/CAP_project#291]
@HereAround :
Unfortunately, I just realized that the convention of the grading both in `GradedRows` and `GradedColumns` is wrong.

```
gap> S := GradedRing( Q * "x, y" );;
gap> SetWeightsOfIndeterminates( S, [ 1, 1 ] );;
```

```
gap> A := GradedRow( [ [ [0], 1 ] ], S );;
gap> B := GradedRow( [ [ [1], 1 ] ], S );;
gap> matrix := HomalgMatrix( "[ x ]", 1, 1, S );;
gap> alpha_row := GradedRowOrColumnMorphism( A, matrix, B );;
gap> IsWellDefined( alpha_row );
false
```

```
gap> A := GradedColumn( [ [ [0], 1 ] ], S );;
gap> B := GradedColumn( [ [ [1], 1 ] ], S );;
gap> matrix := HomalgMatrix( "[ x ]", 1, 1, S );;
gap> alpha_col := GradedRowOrColumnMorphism( A, matrix, B );;
gap> IsWellDefined( alpha_col );
false
```
In both cases, I would expect `true` as an answer, since maps S ->S(1) should correspond to degree 1 elements (O(1) has global sections, but not O(-1)).

This is not just in error in the `IsWellDefined` methods. The degrees of the generators for syzygies are also set w.r.t. the wrong convention.

**Comment by HereAround** [comment]
I propose a fix: https://github.com/homalg-project/CAP_project/pull/293
