### ISSUE TITLE
Display-dilemma in tests of FreydCategory

### ISSUE THREAD

**Issue by HereAround** [homalg-project/CAP_project#330]
As mentioned in https://github.com/homalg-project/CAP_project/pull/325, the tests of FreydCategoriesForCAP are very sensitive to changes to the display methods, since I used these for the tests of graded rows/columns and their Freyd categories. The motivation for this was to create a nice documentation.

Still, this requires frequent changes to the test files. We should think of a better solution.

**Comment by HereAround** [comment]
Proposal to solve this problem is as follows:

1. Avoid ViewString
2. Use display only when meaningful for the documentation. In this case, enclose it in a "og-environment of autodoc.

**Comment by sebastianpos** [comment]
Closed by #332.
