### ISSUE TITLE
FreydCategories: Organization of documentation

### ISSUE THREAD

**Issue by HereAround** [homalg-project/CAP_project#333]
From my point of view, the content of the manual need to be organized differently. Here are some suggestions:

- The content of the documentation of rows and graded rows should be structured in the same way. Likewise for (graded) columns.
- Do we want a large chapter on all example at the end of the manual? Alternatively, one could place the examples right after the structures in question have been introduced.
- In any case, the examples on Rows and Columns need to be placed in the appropriate location of the manual. Currently they are in an individual chapter in the middle of the manual.
- Examples on FreydCategories( graded rows ) should appear after examples on graded rows. Likewise for (graded) columns.
- Some chapters need content. For example "additive closure", "Adelman category", "CokernelImageClosure", "FreydCategory", "Quiver rows"...
- Examples/Tests are not formatted appropriately to be displayed in the pdf. See e.g. "Adelman category basics for category of rows" on page 40ff.
- We should make sure to avoid deprecated functions of autodoc. For example we should use @InsertChunk instead of deprecated @InsertSystem (c.f. https://github.com/homalg-project/homalg_project/pull/261).

**Comment by sebastianpos** [comment]
- we should address objects in the underlying category with small letters and objects in the Freyd category with capital letters
