### ISSUE TITLE
Final derivations as bundles

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/CAP_project#382]
#316 introduced final derivations as bundles.
There are still the following issues:
- #316 makes given mulitplicities in final derivations superfluous and they should thus be deleted from the interface
- final derivations are marked as being installed primitively (apparently this has always been the case). This should be fixed.

**Comment by zickgraf** [comment]
Two other issues should be fixed in this context: #588 and #590.

**Comment by zickgraf** [comment]
Both points are fixed:
* As explained [here](https://github.com/homalg-project/CAP_project/issues/590#issuecomment-1237684820), multiplicities are now required again.
* Final derivations were never regarded as primitive w.r.t. ListPrimitivelyInstalledOperationsOfCategory, but they were regarded as primitive by DerivationsOfMethodByCategory. This has already been fixed some time ago in 0863664635dbc3d61d2835a187a3bd32308344bc.
