### ISSUE TITLE
Intelligent data structure for modules.

### ISSUE THREAD

**Issue by sebasguts** [homalg-project/CAP_project#4]
<a href="https://github.com/sebasguts"><img src="https://avatars.githubusercontent.com/u/1068084?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sebasguts](https://github.com/sebasguts)**
_Wednesday Sep 03, 2014 at 12:16 GMT_
_Originally opened as https://github.com/sebasguts/CAP/issues/4_

---

Implement a module category (based on [MatricesForHomalg](http://github.com/homalg-project/MatricesForHomalg) and [Modules](http://github.com/homalg-project/Modules)) which is stupid, i.e. cannot change the representation of a module.
Based on this category, implement an intelligent data structure for modules which can use several representations using functors.

**Comment by sebasguts** [comment]
<a href="https://github.com/sebasguts"><img src="https://avatars.githubusercontent.com/u/1068084?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sebasguts](https://github.com/sebasguts)**
_Thursday Sep 25, 2014 at 12:11 GMT_

----

First module category can be found in www.github.com/sebasguts/ModulePresentationsForHomalg

**Comment by sebastianpos** [comment]
A first realization of an intelligent data structure for modules was done in:
https://github.com/mohamed-barakat/M2

@mohamed-barakat Do you agree that we can close this issue
and that one can follow the progress on this issue via the above
mentioned repository?
