### ISSUE TITLE
Allow several categories of Rows/Cols for one single ring

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/CAP_project#420]
At the moment, the category of rows/cols is an attribute of the ring.
I'm planning to change that in order to allow multiple versions of the category of rows/cols.
In particular, there may coexist a "clever" and a "workhorse" version within the same session.

I will provide a PR in the near future.

**Comment by mohamed-barakat** [comment]
Will they be attributes with different names?

**Comment by sebastianpos** [comment]
Since I want to allow arbitrary many categories, no.
