### ISSUE TITLE
Error when adding primitive operations with certain input filters (IsList)

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/CAP_project#437]
Here is an example:
```
LoadPackage( "LinearAlgebraForCAP" );
Q := HomalgFieldOfRationals( );;
cat := MatrixCategory( Q : FinalizeCategory := false );
AddRandomObjectByList( cat, {cat,L} -> ZeroObject( cat ) );
Finalize( cat );
RandomObjectByList( cat, [421] );
Error, List Element: <list>[1] must have an assigned value in
  input_sanity_check_functions[i]( arg[i], i );
```

**Comment by sebastianpos** [comment]
@zickgraf 
could you please take a look at this?

**Comment by zickgraf** [comment]
Yes, I forgot to handle the case that an input filter is `"category"`,sorry :/ Is there any meaningful check for something being a CAP category except that it lies in `IsCapCategoryObject`?

**Comment by sebastianpos** [comment]
You mean `IsCapCategory`?
No, I don't think so.

**Comment by zickgraf** [comment]
Yes, I mean `IsCapCategory`, I was confused by the function `CREATE_CAP_CATEGORY_OBJECT` which creates a GAP object which is a CAP category :D I will create a PR now.
