### ISSUE TITLE
ComplexesForCAP cannot be loaded

### ISSUE THREAD

**Issue by HereAround** [homalg-project/CAP_project#453]
I have just pulled the latest version of CAP (e307b000639297bc91b48720f3c92cf6a3a0c293) and of the homalg_project (9a216d7a9f416d98926a3d48aa3fce0722539e69). Unfortunately, I am now unable to load ComplexesForCAP (and in consequence also FreydCategories).

On trying to load this package, I obtain the following error:

Syntax warning: Unbound global variable in /gap-4.10.0/local/pkg/ComplexesForCAP/lib/categories.gi:2150
    AddInterpretMorphismAsMorphismFromDinstinguishedObjectToHomomorphismStructure( category,

[I can also reproduce this issue on Plesken.]

**Comment by kamalsaleh** [comment]
You need to pull the package to comply with the typo fix you mentioned!. See https://github.com/homalg-project/ComplexesForCAP/commit/2a6148f9b9b69bfa666e89c5b253fcd020fbe829

**Comment by HereAround** [comment]
Thanks Kamal. That was too obvious (I assumed this was Package was part of the CAP_project). Issue resolved.

Related: Maybe ComplexesForCAP could become part of the CAP_project?
