### ISSUE TITLE
Sanity checks for final derivations raises errors when ...

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/CAP_project#464]
... adding a (final) derived method to CAP, like this:
```
Add(Final)Derivation(ToCAP)( XX,
         [ [ YY, weight ] ],
   function( cell )
      # some code that needs YY
      # some code that needs the operation XX in another 
      # category that already can compute XX
end : etc .... );
```
Then one gets an error message while loading CAP:

```
Error, final derivation with description
Adding XX using etc ...
   uses XX,
   which is not part of its condition ..
```

I think adding an optional argument which contains a list of the operations to be ignored would solve the problem.

Current example: The final derivation of `BasisOfExternalHom` in `DerivedMethods.gi`.

**Comment by zickgraf** [comment]
c5ff6260c9dcafe818e4818a39dcdbfe3a729adf allows to detect the other category using the automatic mechanism. In particular, there will be no error anymore.
