### ISSUE TITLE
Example from the manual does not work

### ISSUE THREAD

**Issue by felixwellen** [homalg-project/CAP_project#518]
In the manual:

https://github.com/homalg-project/CAP_project/blob/master/CAPManual.pdf

The introductory example with the category of groups (p. 5, 6) fails with the following error message when constructing the identity of the group S3:

gap>  id_S3 := IdentityMorphism( S3);
Error, in function IdentityMorphism
       of category groups:
       the result does not lie in the filter IsCapCategoryMorphism.
 at /proc/cygdrive/C/gap-4.11.0/pkg/CAP-2019.06.07/gap/InstallAdds.gi:64 called from
CAP_INTERNAL_DISPLAY_ERROR_FOR_FUNCTION_OF_CATEGORY( record.function_name, category,
 "the result does not lie in the filter IsCapCategoryMorphism."
 ); at /proc/cygdrive/C/gap-4.11.0/pkg/CAP-2019.06.07/gap/InstallAdds.gi:323 called from
CallFuncList( func, arg ) at /proc/cygdrive/C/gap-4.11.0/pkg/ToolsForHomalg-2019.09.02/gap/CachingObjects.gi:775 called from
<function "IdentityMorphism method">( <arguments> )
 called from read-eval loop at *stdin*:16
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>

**Comment by zickgraf** [comment]
This is the result of #269. The manual should execute
```
EnableAddForCategoricalOperations( grps );
```
after creating the category.

**Comment by felixwellen** [comment]
Yes, that solves the problem for me.

**Comment by sebastianpos** [comment]
Thank you very much for pointing that out.

I'm also very sorry for the error, the manual hasn't been updated for quite a while now. Please note that there still is an open issue concerning the manual: #266
