### ISSUE TITLE
Calling CreateCapCategory multiple times with same argument

### ISSUE THREAD

**Issue by oysteins** [homalg-project/CAP_project#53]
If I call CreateCapCategory twice with the same string as argument, I get the same category object both times:

    gap> x:=CreateCapCategory("x");
    x
    gap> y:=CreateCapCategory("x");
    x
    gap> IsIdenticalObj(x,y);
    true

Is this correct?  The documentation for CreateCapCategory says "This operation creates a new CAP category from scratch".  This does not seem to be the case in the second call above, since the return value is just the same object I had before.

The same thing happens if I call the zero-argument version of CreateCapCategory after first creating a category with the name it wants to use:

    gap> z:=CreateCapCategory("AutomaticCapCategory1");
    AutomaticCapCategory1
    gap> w:=CreateCapCategory();
    AutomaticCapCategory1
    gap> IsIdenticalObj(z,w);
    true

**Comment by sebastianpos** [comment]
CreateCapCategory was equipped with a cache, which we now
removed. So if you now create two categories with the same
name, you will get two different categories.
