### ISSUE TITLE
IsEqualForCacheForMorphisms does not default to IsEqualForMorphismsOnMor in all cases

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#583]
From the documentation of `AddIsEqualForCacheForMorphisms`:

> By default [`IsEqualForCacheForMorphisms`] is an alias for `IsEqualForMorphismsOnMor`, where fail is substituted by false.

However, the following example shows that this is not necessarily true:

```
LoadPackage( "CAP" );

cat := CreateCapCategory( );
myobj := SymmetricGroup( 3 );
AddObject( cat, myobj );
mymor1 := GroupHomomorphismByImages( myobj, myobj );
AddMorphism( cat, mymor1 );
mymor2 := GroupHomomorphismByImages( myobj, myobj );
AddMorphism( cat, mymor2 );

AddIsCongruentForMorphisms( cat, function( a, b )
	
	return true;

end );

Finalize( cat );

Display( IsEqualForMorphismsOnMor( mymor1, mymor2 ) );
Display( IsEqualForCacheForMorphisms( mymor1, mymor2 ) );
```

displays

```
true
false
```

The reason is the following: there is a derivation setting `IsEqualForCacheForMorphisms` to `IsIdenticalObj` if `IsCongruentForMorphisms` is installed and `IsEqualForMorphisms` is not (yet) installed. In the above example, this derivation is triggered with weight 1. Afterwards, `IsEqualForMorphisms(OnMor)` is derived from `IsCongruentForMorphisms` and the usual derivation of `IsEqualForCacheForMorphisms` from `IsEqualForMorphismsOnMor` is triggered, but with weight 203, so it is not installed.

I'm not sure if this is a bug, or if the behaviour is intended (in order to not use the possibly expensive `IsCongruentForMorphisms` for cache comparisons) and the documentation should be changed.

Edit: Another problem: the final derivations for `IsEqualForCacheForMorphisms` to not have `IsEqualForCacheForMorphisms` in their exclude list and thus overwrite user a user given `IsEqualForCacheForMorphisms`.

**Comment by sebastianpos** [comment]
I think a good default behaviour should be:
- Set `IsEqualForCache` to `IsIdenticalObj` by default, both for objects and morphisms

Thus, the documentation should be changed.



> Edit: Another problem: the final derivations for `IsEqualForCacheForMorphisms` to not have `IsEqualForCacheForMorphisms` in their exclude list and thus overwrite user a user given `IsEqualForCacheForMorphisms`.

This is strange. I don't understand why the function is overwritten, since its weight should be higher than a user given function.

**Comment by zickgraf** [comment]
> Set IsEqualForCache to IsIdenticalObj by default, both for objects and morphisms

Sound like a good idea. In that case we could drop all derivations, as the default of `IsEqualForCache` in `ToolsForHomalg` is `IsIdenticalObj` anyway, is that correct?

> This is strange. I don't understand why the function is overwritten, since its weight should be higher than a user given function.

I just checked again, and we are both partially correct :D When `IsEqualForCacheForMorphisms` is derived from `IsEqualForMorphismsOnMor` it has weight 203 and thus does not overwrite a user given function (with default weight). However, when it is derived from `IsIdenticalObj`, it has weight 1 and thus does overwrite a user given function (with default weight). You can check by adding
```
AddIsEqualForCacheForMorphisms( cat, function( a, b )
	
	return true;

end );
```
to the example above.

**Comment by sebastianpos** [comment]
> Sound like a good idea. In that case we could drop all derivations, as the default of `IsEqualForCache` in `ToolsForHomalg` is `IsIdenticalObj` anyway, is that correct?

Yes, that's what the documentation says.
And yes, let's simply try and drop all derivations.

>  just checked again, and we are both partially correct :D

Oh, I see. Since `IsIdenticalObj` has no weight at all, this derivation is actually so cheap (0 + 1 = 1) that it overwrites any user given function whose weight is not manually set. This was not intentional ;-) But it also points to the fact that `IsIdenticalObj` should really be the correct default choice here.
