### ISSUE TITLE
Allowing fail for IsEqualForObjects

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#595]
Objective:
I would like to allow to return the value `fail` in `IsEqualForObjects` (and maybe also for `IsEqualForMorphisms` as a second step).

Reasoning:
In `GradedCategories` our objects are infinite lists which we cannot compare in finite time. Thus, we have to use `IsIdenticalObj` for comparing objects and crisp caching for fulfilling the specifications. However, I have noticed two things:
1. On a technical level, CAP uses `IsEqualForObjects` only for input sanity checks and a small number of derivations (e.g., IsEndomorphism, IsIdenticalToIdentityMorphism, ...). If I do neither need input sanity checks (of course, my code is always 100% perfect!!! :D) nor one of the derivations, on a technical level I do not need `IsEqualForObjects`.
2. On an abstract level I know that all of the algorithms give equal output for equal input, that is, for any finite sublist the specification is actually fulfilled.

Thus, since all results I consider only depend on finite sublists, I think I do not actually have to use crisp caching. However, if I disable it, of course the sanity checks fail. I have tested disabling both the caching and the input sanity checks and all tests pass.

I have thought about how one could properly support this in CAP (except simply disabling input sanity checks), and I think returning `fail` for `IsEqualForObjects` for two non-identical objects would express exactly what I want: "Sorry, I do not know how to compare these two objects in finite time, but you can assume that you can work with them".

Implementation:
I would adapt the input sanity checks to simply continue if `fail` is returned by `IsEqualForObjects`, and think about the derivations on a case by case basis.

Question:
Have I missed something why I would really need crisp caching in this case? If not, do you like the idea?

Note: This is not urgent right now for me, but I expect that I would like to have this in the future, for example when using `CompilerForCAP` on categories with `IsIdenticalObj` for the equality of objects.

**Comment by sebastianpos** [comment]
Are you sure that you cannot achieve a proper `IsEqualForObjects` in your situation?
For example if your infinite lists are based on an underlying function, can it help to simply compare the Strings of these underlying functions?

Moreover, if you simply "know" that your setup is correct, then deactivating both the crisp caching and the sanity checks for your category already appears to be the correct move.

**Comment by zickgraf** [comment]
> Are you sure that you cannot achieve a proper IsEqualForObjects in your situation?
> For example if your infinite lists are based on an underlying function, can it help to simply compare the Strings of these underlying functions?

We currently have some assumptions which would make this really hard. For example, we check that the underlying category is skeletal, so we can be sure that `DirectSum( O, O ) = TensorProductOnObjects( O, A )` for the zero object `O` and another object `A`. Incorporating this into a comparison algorithm for functions seems non-trivial. And even if we did not have such conditions/assumptions, I did not want venture in this direction, as I have the feeling it would create more problems than it would solve.

> Moreover, if you simply "know" that your setup is correct, then deactivating both the crisp caching and the sanity checks for your category already appears to be the correct move.

Some parts of the input sanity checks work without any problems, for example testing that objects lie in the correct category and have all required filters. Thus, it would be nice if I would not have to disable the checks completely. Also, for debugging purposes I could maybe let `IsEqualForObject` compare the first 100 entries and return `false` if I find a difference and `fail` else. This way I could still make use of the sanity checks (without risking to erroneously identify two objects by simply returning `true` when finding no difference in the first 100 entries).

**Comment by sebastianpos** [comment]
>  Incorporating this into a comparison algorithm for functions seems non-trivial

I don't understand the example. I really meant a trivial comparision: `String( f ) = String( g )`, without bothering about the semantics of `f` or `g`. 

I'm very reluctant to give up the idea that `IsEqualForObjects` should be decidable, since it incorporates the whole idea of being able to type check your category.

**Comment by sebastianpos** [comment]
Maybe we should rather discuss about how to make disabling sanity checks more flexible.

Is it correct that in your situation you would like to have a switch to turn off any sanity check that involves `IsEqualForObjects`, `IsEqualForMorphisms` (which for me would be equivalent to turn off CAP's own kind of type check), but to keep sanity checks that are not of this type (which for me appears to be any filter check by GAP which by GAP's design must yield true or false anyway, and thus is always applicable)?

We could think about that not providing an `IsEqualForObjects` function to a category automatically disables type checks in the way specified above (and maybe print a warning).

Concerning the desire to debug, I don't see the advantage of returning `fail` instead of `true`, since in both cases, the computation would simply carry on.

**Comment by zickgraf** [comment]
> I don't understand the example. I really meant a trivial comparision: `String( f ) = String( g )`, without bothering about the semantics of `f` or `g`.

I thought that this equality should model the abstract equality I have in mind, which would need more semantics. But now I understand that this is not necessary. Thus, now I like this idea, yet I do not understand how it would work. For example, consider the function for `TensorProductOnObjects` of two objects `A` and `B`:
```
f :=
  function ( n )
    local indices;
    
    indices := TensorProductIndices( A, B );
    
    if indices = [ ] then
        return ZeroObject( CapCategory( A )!.UnderlyingCategory );
    fi;
    
    return DirectSum( List( indices, i -> TensorProduct( A[i], B[n - i] ) ) );
    
end;
``` 
How would I distinguish the outputs for different inputs when only comparing via functions? Of course I could keep references to `A` and `B` to compare recursively, but then I would model something like the genesis in `LazyCategories`, I think.

(Note: to keep the discussion compact, I think I will not respond to the points in your second message until we have reached a conclusion on the topic of this message, if that's okay. Thanks for discussing all these things in such detail! :-) )

**Comment by sebastianpos** [comment]
> How would I distinguish the outputs for different inputs when only comparing via functions? Of course I could keep references to `A` and `B` to compare recursively, but then I would model something like the genesis in `LazyCategories`, I think.

Right, you would need a "compiled down" version of that function.

**Comment by sebastianpos** [comment]
Is that achievable in your case via `CompilerForCAP`? :-)

**Comment by zickgraf** [comment]
> Is that achievable in your case via `CompilerForCAP`? :-)

It should be possible, and I think it would essentially model the genesis of an object/morphism like `LazyCategories` does, so this could even be achieved without the compiler. Comparing via the genesis would actually be interesting more general as a "fallback" equality as it should give a "correct" equality for any category fulfilling the specifications I think. But this seems like a larger project to me and I fear that storing/comparing the genesis might get expensive, so maybe we could nevertheless discuss the original idea regarding sanity checks.

So from the comment above:

> Is it correct that in your situation you would like to have a switch to turn off any sanity check that involves IsEqualForObjects, IsEqualForMorphisms (which for me would be equivalent to turn off CAP's own kind of type check), but to keep sanity checks that are not of this type (which for me appears to be any filter check by GAP which by GAP's design must yield true or false anyway, and thus is always applicable)?

Yes, that's correct!

> We could think about that not providing an IsEqualForObjects function to a category automatically disables type checks in the way specified above (and maybe print a warning).

Abstractly, this is exactly what I had in mind: Currently, if one does not provide `IsEqualForObjects`, CAP falls back to `ReturnFail` (with the case of identical objects handled by a redirect function):
https://github.com/homalg-project/CAP_project/blob/8f81dbf1e4ee74ed1d7aa26f7c785f3df45e191a/CAP/gap/DerivedMethods.gi#L3410-L3414

This is outside of the specification of the manual:
> The arguments are two objects a and b. The output is true if a = b, otherwise the output is false.

Yet, many existing derivations and pre functions already handle this case explicitly:
https://github.com/homalg-project/CAP_project/blob/8f81dbf1e4ee74ed1d7aa26f7c785f3df45e191a/CAP/gap/DerivedMethods.gi#L921-L934
https://github.com/homalg-project/CAP_project/blob/8f81dbf1e4ee74ed1d7aa26f7c785f3df45e191a/CAP/gap/MethodRecord.gi#L16-L18

So I thought it would be the perfect mechanism to use for what I want.

> Concerning the desire to debug, I don't see the advantage of returning fail instead of true, since in both cases, the computation would simply carry on.

If I apply `IsEqualForObjects` manually, I would not like to get `true` if the real answer is "I cannot tell". Of course, I could then ask `IsIdenticalObj` to distinguish the two cases, but since GAP explicitly provides a third option, it would be nice to simply use this option, I think.

**Comment by sebastianpos** [comment]
I was not aware of the current default `ReturnFail` implementation, and if it wasn't for this issue, I maybe would have tried to delete it, since it implies that `IsEndomorphism` is always declared to be "computable" even though the result might be `fail`.

Okay, if the ramifications turn out to be not too wild, we can try and relax the two equality notions for objects and morphisms, using your suggested interpretation: "I, the user, know the underlying notion of equality that satisfies the specification, but I'm not going to tell it the system (since that might be too complicated or since I am too lazy), and I release CAP from its responsibility to do the type checking for me".

In such cases, I highly encourage to document the equality notion, since it cannot be defered from the code anymore.

Okay, for the implementation, what about the following idea: we could delete all final derivations w.r.t. equalities and simply install two operations for CapCategoryObjects/Mors with `ReturnFail`. By doing so, `CanCompute` of the equality notions would not be set to `true`, and derivations would not falsely be triggered.

**Comment by zickgraf** [comment]
Sound good! :-) I will prepare a PR, and if I find larger ramifications than the ones already discussed I will get back to this issue.

**Comment by sebastianpos** [comment]
Great, thanks a lot!



> and simply install two operations for CapCategoryObjects/Mors with `ReturnFail`.

maybe `IsIdenticalObj` should be tested first before the call of `ReturnFail` here.

**Comment by zickgraf** [comment]
The application which motivated this issue is dead, so I will close the issue.
