### ISSUE TITLE
Implementation of complexes

### ISSUE THREAD

**Issue by sebasguts** [homalg-project/CAP_project#6]
<a href="https://github.com/sebasguts"><img src="https://avatars.githubusercontent.com/u/1068084?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sebasguts](https://github.com/sebasguts)**
_Wednesday Sep 03, 2014 at 12:33 GMT_
_Originally opened as https://github.com/sebasguts/CAP/issues/6_

---

First implementation of complexes can be done as a functor from Integers into a category.
There are several requirements for this data structure:
- **Lazy evaluation**: Morphisms of complex should be computed lazy, i.e. when needed.
- ....

**Comment by sebastianpos** [comment]
A more advanced data structure for complexes is implemented in:
https://github.com/kamalsaleh/ComplexesForCAP

@kamalsaleh Do you agree that we can close this issue
and that one can follow the progress on this issue via the above
mentioned repository?

**Comment by kamalsaleh** [comment]
Yes, I would recommend using the repo in [https://github.com/homalg-project/ComplexesForCAP](url) since it could be more  stable than that in my repo.

**Comment by sebastianpos** [comment]
Very good.
