### ISSUE TITLE
Releases for all packages

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#604]
If all packages had releases, I could simplify `PackageJanitor` quite a bit (for example, I would not have to check if a package has HTML documentation). Thus, I would like to add releases for all packages in `CAP_project`. Would that be okay? I could even enable automated releases if you like.

**Comment by sebastianpos** [comment]
Yes, that would be okay. And automated releases are also a good idea :)

**Comment by zickgraf** [comment]
Note: With automated releases, you should not push to/merge into master as long there is a CI job running which will trigger a release (usually because a version number was incremented). Otherwise we get race conditions and the CI fails. For jobs not triggering a release this is not a problem.
