### ISSUE TITLE
GradedRow/Column

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#637]
I wanted to start using `CategoryOfGradedRows/Columns` but stumbled over the following unexpected behavior:

Unlike `GradedModules` and `AdditiveClosure` the constructors `GradedRow`/`GradedColum` seem to sort/collect the degrees before creating the object. I wonder how this could work with the homogeneous matrices of homalg. For this to work properly one has to keep sorting the columns and rows of the matrices accordingly. Am I missing something here?

**Comment by sebastianpos** [comment]
As far as I can see the constructors don't sort the degrees.

Why do you think that they do?

**Comment by mohamed-barakat** [comment]
Sorry, I misinterpreted the behavior of `CAP_CATEGORY_OF_GRADED_ROWS_AND_COLUMNS_INTERNAL_SIMPLIFY_DATA_STRUCTURE`. The comment there is stating clearly:
```
# run once accross the degree list and add successive equal degrees
# example:
# [[ a,1 ], [ a,1 ], [ b,1 ], [a,2 ]] -> [[ a,2 ], [ b,1 ], [ a,2 ]]
# BUT this gets not simplified to say [[ a,4 ], [ b,1 ]]
```
