### ISSUE TITLE
Attaching constructors to the category

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#660]
For the compiler and general beauty I would like to attach the constructors for objects and morphisms to their category. To this end, I propose to add two new CAP operations:
1. `ObjectConstructor` with `filter_list := [ "category", IsObject ]` and
2. `MorphismConstructor` with `filter_list := [ "category", "object", IsObject, "object" ]`.

With these, one can attach the constructors to the category simply by calling `AddObjectConstructor` and `AddMorphismConstructor` as usual. An example implementation with application to `LinearAlgebraForCAP` can be found here: 0db6032336eabffc059d1c1924fbad7e23e8ce42

One could use this system in several different ways:
1. Not at all (existing categories/constructors are not affected).
2. Add `ObjectConstructor` and `MorphismConstructor` as technical constructors and create `MyNiceConstructor` (which then calls `ObjectConstructor` resp. `MorphismConstructor`) for users.
3. Use `DeclareSynonym` to make `MyNiceConstructor` an alias of  `ObjectConstructor` resp. `MorphismConstructor`, so the user can use a nice name.
4. Only provide `ObjectConstructor` and `MorphismConstructor`.

So this system would be very flexible. There two downsides which come to my mind:
1. If objects or morphism are not given by a single datum, one has to bundle them into a single list or record.
2. One can only attach a single object constructor and a single morphism constructor to a category (one could use additional filters in the `Add` methods but these would be incompatible with the compiler).

However, I do not know of any examples where these two points would be relevant (I know of categories with multiple constructors, but there is always a main constructor and the other ones are simply convenience).

@sebastianpos @kamalsaleh @mohamed-barakat I would be happy to hear if this system would suit your applications or if you see any problems :-)

**Comment by kamalsaleh** [comment]
Since they are optional, they can do only good :). These two methods are not categorical, would it be possible to include a brief  documentation to them? For example, a string which explains what exactly is `IsObject`? I think they should also be added to the list https://github.com/homalg-project/CAP_project/blob/406e31bd5032abdf2427b17c54472e7c12c2714e/CAP/gap/CAP.gi#L218-L225

**Comment by zickgraf** [comment]
> For example, a string which explains what exactly is `IsObject`?

These are the "object datum" and "morphism datum", which depend on the input category. For example, for `LinearAlgebraForCAP` it would be the dimension (for objects) and a homalg matrix (for morphisms). Do you think it needs more documentation than what I have written in the line below?
https://github.com/homalg-project/CAP_project/blob/0db6032336eabffc059d1c1924fbad7e23e8ce42/CAP/gap/CategoryMorphisms.gd#L68

> I think they should also be added to the list

Good idea! In some categories, caching might actually make sense (for example, in `LinearAlgebraForCAP` the object constructor `MatrixCategoryObject` currently is a key dependent operation), so I would not set it to `never` but to `none`.

**Comment by kamalsaleh** [comment]
I always find myself going to the package .gd's or its manual.pdf to see what are the object/morphism constructors and how to use them, and I always wished those can be equipped (somehow) with the category itself. In other words, I wish I can ask the category about the type and semantic of its objects and morphisms instead of guessing that from the manuals. For example, in the category of complexes there might be two objects datum: `["list_of_diffs", "lower_bound"]` or `z_function`.

Anyway, after reading your description again, these two operations are rather technical and its desirable  for users to use the `Nice Constructors`.

**Comment by zickgraf** [comment]
> In other words, I wish I can ask the category about the type and semantic of its objects and morphisms instead of guessing that from the manuals.

That would be nice indeed. I cannot think of a clean technical interface to incorporate this in the current setup, but: The object and morphism constructors should do type checking anyway and should provide useful errors in case of a failure. So you could simply call `ObjectConstructor( category, fail )` and should get a helpful error message describing what the object datum should be (except in the case where `fail` would actually be a valid input, but that should be rare I assume :D ).

> For example, in the category of complexes there might be two objects datum: `["list_of_diffs", "lower_bound"]` or `z_function`.

That's an interesting example. If I read the code in `HigherHomologicalAlgebra/ComplexesCategories/gap/Complexes.gi` correctly, both variants ultimately use `CHAIN_OR_COCHAIN_COMPLEX_BY_Z_FUNCTION`, correct? Then you could probably add `CHAIN_OR_COCHAIN_COMPLEX_BY_Z_FUNCTION` as `ObjectConstructor` to the category. This way you could also get rid of the third argument `type` of `CHAIN_OR_COCHAIN_COMPLEX_BY_Z_FUNCTION`, because that would already be encoded in the category :-)

**Comment by zickgraf** [comment]
This is now implemented in 85831840172b040eca91a82b1a4811e7674bbed3 together with two "inverse" operations `ObjectDatum` and `MorphismDatum`. I have marked these operations as "experimental" so we can still change the specification should the need arise. I plan to use them in several categories and drop the "experimental" state in some weeks.
