### ISSUE TITLE
dual_postprocessor_func of BasisOfExternalHom

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#672]
The `dual_postprocessor_func` of `BasisOfExternalHom` is currently set to `IdFunc`. According to the documentation, the result of `BasisOfExternalHom` should be a list of morphisms in the same category as the input. Thus, I think choosing `IdFunc` for `dual_postprocessor_func` is wrong and the correct value should be `CAP_INTERNAL_OPPOSITE_RECURSIVE` (which is the default). Is this correct?

cc @mohamed-barakat who is the author of that code according to git-blame.

**Comment by mohamed-barakat** [comment]
@kamalsaleh: Could you please have a look at it?

**Comment by kamalsaleh** [comment]
Fabian is right, it is a bug. The above PR should fix it.

**Comment by mohamed-barakat** [comment]
Thanks @zickgraf for reporting and @kamalsaleh for fixing 😊
