### ISSUE TITLE
Proposal: Disallow `fail` for Lift, Colift and SolveLinearSystemInAbCategory

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#673]
As far as I am aware, `Lift`, `Colift` and `SolveLinearSystemInAbCategory` are the only remaining CAP operations, where `if ... else ...` constructions occur in the implementation, due to possibly returning fail. This currently is a major problem for `CompilerForCAP`, because in towers of categories this leads to nested `if ... else ...` statements which are hard to simplify in a generic way.

According to @mohamed-barakat, all of his applications fall into one of the following two cases: Either one knows a priori (mathematically) that the lift etc. exists, or one wants to decide if the lift exists (without actually computing a lift). The second case is already covered by `IsLiftable` etc.

Thus, I propose we tighten the specification of `Lift` etc. to assume that the lift exists. Of course it would be nice to do this in a backwards compatible manner, but that would mean we need a new operation `LiftWithGivenExistence` which would be weird when compared to `LiftAlongMonomorphism`, for example.

Should the need arise that one wants to decide if a lift exists and compute one at the same time, we could reintroduce the existing behavior via a operation `LiftOrFail` which would be ignored by the compiler.

**Comment by sebastianpos** [comment]
I'm fine with changing the specification if it's beneficial for the compiler, but I would also like to keep `XOrFail` versions of the commands for 2 reasons:
1) I use it in the Adelman implementation, e.g., here https://github.com/homalg-project/CAP_project/blob/f95bb0caf530028002c8f1d74e99b13c60731dea/FreydCategoriesForCAP/gap/AdelmanCategory.gi#L323
where `WitnessPairForBeingCongruentToZero` calls `SolveLinearSystemInAbCategory`.
2) I like the 3 commands from the user's POV. When experimenting, I'm often unaware of the a priori existence of a solution, and raising an error is an unpleasant way to tell the user that no solution exists.

**Comment by zickgraf** [comment]
I agree that having `XOrFail` is a good idea, it also makes life easier for me when adapting existing code :D

But regarding 1.: I think this code should use `MereExistenceOfSolutionOfLinearSystemInAbCategory`, with the benefit that this might be much faster (for example, on the homalg level `DecideZeroRows` is much faster than `DecideZeroRowsEffectively`). If you agree, I will adjust the code.

@kamalsaleh Grepping through `HigherHomologicalAlgebra`, I see a lot of checks of the kind `if Lift( ... ) = fail then ...` (or `Colift` or `SolveLinearSystemInAbCategory`). Would my proposal negatively affect you? I could provide a PR which simply replaces `Lift( ... )` by `LiftOrFail( ... )`, but if categories do not natively implement `LiftOrFail` this is slower than the current `Lift` (because it will first check `IsLiftable` and then call `Lift`).

**Comment by kamalsaleh** [comment]
Go ahead and implement your proposal. I am sure complying with the new specifications would improve the existing code in `HigherHomologicalAlgebra`. A large part of it was implemented before we even have `IsLiftable` alike operations. There is no need to provide a PR because I might need different adjustments in different contexts.
