### ISSUE TITLE
The default caching for Object/MorphismConstructors slows computation

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/CAP_project#695]
Currently, the `ObjectConstructor` and `MorphismConstructor` in a category C are basic operations, so they inherit the same caching of C. In  `LinearAlgebraForCAP` all basic methods create their output using `ObjectConstructor` and `MorphismConstructor` which are now also cached. This causes a major performance regression.

In some categories it might be helpful in `Algebroids` but in `LinearAlgebraForCAP` not that much :/ 

```
LoadPackage( "DerivedCategories" );
EnhanceAllPackages();
Q := HomalgFieldOfRationals( );
A := RandomQuiverAlgebraWhoseIndecProjectiveRepsAreStrongExceptionalCollection( Q, 5, 10, 5 );

Q_mat := MatrixCategory( Q );
A_oid := Algebroid( A : range_of_HomStructure := Q_mat );
K_A_oid_plus := HomotopyCategory( AdditiveClosure( A_oid ) );

o := RandomObject( K_A_oid_plus, [-4,4,3] );

# (1)
DeactivateCachingObject( Q_mat!.caches.MorphismConstructor );
B := CallFuncListWithTime( BasisOfExternalHom, [o,o] );;
# 20.967779 Secs.
Size(B);
# 16
Q_mat!.caches.MorphismConstructor;
# <A cache with 0 hits and 0 misses>


# (2)
B := CallFuncListWithTime( BasisOfExternalHom, [o,o] );;
# 39.058862 Secs.
Size(B);
# 16
Q_mat!.caches.MorphismConstructor;
# <A cache with 95 hits and 10676 misses>
```

**Comment by zickgraf** [comment]
> ```
> # <A cache with 95 hits and 10676 misses>
> ```
Oh dear :D

There are four ways forward:
1. Deactivate the caching of `MorphismConstructor` in `LinearAlgebraForCAP` only.
2. Set the default cache type of `MorphismConstructor` to `none`.
3. Set the default cache type of `MorphismConstructor` to `never`.
4. Disable caching of all CAP operations by default.

Option 2 would lead to the following situation: If the user deactivates caching and activates it again, the caching of `MorphismConstructor` is activated, i.e., different from the default. I think this would be unexpected for users and, thus, a violation of the "principle of least surprise".

Option 3 would have the drawback that the user could never activate caching for `MorphismConstructor`.

Personally, I would go straight to option 4 but I do not want to choose option this without discussion and Sebastian's consent.

**Comment by kamalsaleh** [comment]
The operation `SetSpecialSettings()` always deactivates the caches of almost all instances, so I would not mind that. 

I think, option (1) is a good hot-fix for now.

**Comment by kamalsaleh** [comment]
https://github.com/homalg-project/CAP_project/pull/696 changes the run-time. It turns out the caching objects is needed for a better performance:

```
# (3)
B := CallFuncListWithTime( BasisOfExternalHom, [o,o] );;
# 60.967779 Secs.
Size(B);
# 16
Q_mat!.caches.ObjectConstructor;
# <A cache with 0 hits and 0 misses>


# (4)
SetCachingToWeak( Q_mat, "ObjectConstructor" );
B := CallFuncListWithTime( BasisOfExternalHom, [o,o] );;
# 11.172617 Secs.
Size(B);
# 16
Q_mat!.caches.ObjectConstructor;
<A cache with 15849 hits and 31 misses>
```

So, you might accordingly adjust `LinearAlgebraForCAP` to cache only the objects.
