### ISSUE TITLE
Identity functor

### ISSUE THREAD

**Issue by oysteins** [homalg-project/CAP_project#70]
I recently tried to find out how to obtain the identity functor of a category in CAP, and it turned out to be more difficult than I expected.  It seems like this is the way to do it:

``` GAP
IdentityMorphism( AsCatObject( cat ) )
```

It took me quite a while to figure this out from the manual, and the resulting code looks somewhat mysterious to anyone who is not a CAP expert.

How about adding an attribute `IdentityFunctor` for categories?  Then the above code could be written simply like this:

``` GAP
IdentityFunctor( cat )
```

This would be a lot more readable, and `IdentityFunctor` would probably be quite easy to find in the manual for anyone who is trying to find out how to get an identity functor.

**Comment by sebasguts** [comment]
Seems reasonable, I will implement this.
