### ISSUE TITLE
GAP version dependency not consistent with code

### ISSUE THREAD

**Issue by oysteins** [homalg-project/CAP_project#71]
CAP uses the GAP builtin function EndsWith, which was introduced in GAP 4.8.  However, in PackageInfo.g, CAP only claims to rely on GAP >= 4.6.

In my GAP 4.7.9 (from Ubuntu 16.04), this happens when I try to load CAP:

```
oysteini@oysteini-laptop:~$ gap
 ┌───────┐   GAP, Version 4.7.9 of 29-Nov-2015 (free software, GPL)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: small 2.1, small2 2.0, id2 3.0, trans 1.0, prim 2.1
 Packages:   GAPDoc 1.5.1, IO 4.4.5
 Try '?help' for help. See also  '?copyright' and  '?authors'
gap> LoadPackage("CAP");
Syntax error: warning: unbound global variable in /home/oysteini/gap/pkg/AutoDoc/gap/Au\
toDocMainFunction.gi line 376
    if not EndsWith(main, ".xml") then
                   ^
──────────────────────────────────────────────────────────────────────────────────────
Loading  AutoDoc 2016.03.08 (Generate documentation from GAP source code)
by Sebastian Gutsche (http://wwwb.math.rwth-aachen.de/~gutsche/) and
   Max Horn (http://www.quendi.de/math).
Homepage: https://gap-packages.github.io/AutoDoc
──────────────────────────────────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────────────────────────
Loading  ToolsForHomalg 2016.02.17 (Provides special methods and knowledge propagation tools)
by Mohamed Barakat (http://www.mathematik.uni-kl.de/~barakat/),
   Sebastian Gutsche (http://wwwb.math.rwth-aachen.de/~gutsche/), and
   Markus Lange-Hegermann (http://wwwb.math.rwth-aachen.de/~markus/).
Homepage: http://homalg-project.github.io/homalg_project/ToolsForHomalg/
──────────────────────────────────────────────────────────────────────────────────────
Syntax error: warning: unbound global variable in /home/oysteini/gap/pkg/CAP/gap/Printi\
ngFunctions.gi line 28
        if EndsWith( current, "Category" ) then
                   ^
Error, Variable: 'EndsWith' must have an assigned value in
  if EndsWith( current, "Category" )  then
    current := current{[ 1 .. Length( current ) - 8 ]};
fi; called from 
<function "__CAP_INTERNAL_RANK_CATEGORY_FROM_METHOD_RECORD">( <arguments> )
 called from read-eval loop at line 
101 of /home/oysteini/gap/pkg/CAP/gap/PrintingFunctions.gi
you can 'return;' after assigning a value
brk> 
```

First there is a syntax error because of the same error in AutoDoc, then there is a syntax error because of the occurence of EndsWith in CAP, and finally GAP ends up in a break loop because CAP attempts to call the function calling EndsWith.

The simple and obvious fix for this is of course to change the GAP version dependency in PackageInfo.g from ">= 4.6" to ">= 4.8".  Then CAP would at least fail in the "proper" way when someone attempts to use it in GAP <4.8.  This does however still mean that anyone who doesn't have a brand-new GAP available will not be able to use CAP (well, at least not without doing some tweaking).

As long as the only reason for requiring GAP 4.8 is the EndsWith function, I guess one could also include some hack like this in order to make CAP usable in older versions as well:

``` GAP
if not IsBound( EndsWith ) then
  # implementation of EndsWith copied from GAP 4.8
  DeclareGlobalFunction( "EndsWith" );
  InstallGlobalFunction(EndsWith, function(string, suffix)
    return Length(suffix) <= Length(string) and
      string{[Length(string)-Length(suffix)+1..Length(string)]} = suffix;
  end);
fi;
```

Come to think of it, if one decides to use a hack like this, it might be best to place it in AutoDoc, since that package also has the same problem and is required by CAP.

**Comment by sebasguts** [comment]
Thanks, that really is a big bug. I think I would vote for making GAP 4.8 a requirement, if thats okay for you.

**Comment by oysteins** [comment]
Well, this depends on to what extent you want to require users of CAP to keep up-to-date with recent GAP releases.

For people who use Ubuntu or Debian (that means more or less everybody, right?), requiring the newest GAP version normally means that they have to install GAP manually instead of using the version from the operating system's package manager.  For instance, the stable releases of these systems at the moment -- Ubuntu 16.04 LTS "xenial" and Debian 8 "Jessie" -- both include GAP 4.7.  They are both relatively recent (released this April and last April, respectively), and will probably be around for quite some time.

Of course, people who are stuck with an old version of GAP could always use an old version of CAP as well.  Maybe you should try to make it easy to find the right version of CAP to download based on the GAP version one is using?  For example, on the [release download page](https://github.com/homalg-project/CAP_project/releases), it could be mentioned which GAP version each of the CAP releases depends on.

**Comment by zickgraf** [comment]
We have decided to always depend on a quite recent GAP version because our test suite does not test old versions and we are often using features from recent GAP versions anyway.
