### ISSUE TITLE
Recent release breaks other packages

### ISSUE THREAD

**Issue by alex-konovalov** [homalg-project/CAP_project#762]
I've accidentally picked it up tonight, and now there are errors like

```
Error, You must pass a pair (i.e. a list of length 2) of strings to `AddCategoricalPr\
operty`. The second entry is the property of the opposite category. If the opposite property is not implemented, you may pass `fail` instead. at /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GAPCO\
PTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-stab\
le-snapshot/pkg/CAP-2021.11-08/gap/CAP.gd:122 called from
```
while loading:
- generalizedmorphismsforcap 
- linearalgebraforcap
- modulepresentationsforcap
- monoidalcategories

I will revert this to stable release of CAP - let me know please when this will be resolved.

**Comment by alex-konovalov** [comment]
P.S. CAP reverted to stable in https://github.com/gap-system/gap-distribution/commit/95f77ad558ecbc3d7d1bd454d9c9767de9cf42df

**Comment by zickgraf** [comment]
Sorry, I forgot to bump the version of `MonoidalCategories` so there was no relase :( Should be fixed once https://github.com/homalg-project/CAP_project/actions/runs/1468823740 succeeds. Thanks for the heads-up!

**Comment by alex-konovalov** [comment]
@zickgraf thanks - reenabled new CAP in https://github.com/gap-system/gap-distribution/commit/e5cece92bb3d81f54ac61840649bc6977d3f8083
