### ISSUE TITLE
Revert #778?

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#779]
@mohamed-barakat With the recent changes in `CategoryConstructor`, could #778 be reverted without breaking `Toposes`? If yes, I would suggest to do so, because I think the old names are more descriptive.

**Comment by TKuh** [comment]
Would it be possible to make these functions anonymous, for example as in [here](https://github.com/homalg-project/CAP_project/blob/master/CAP/gap/MethodRecord.gi#L2973), or is it better not to do so? When I created these DualPreProcessor* functions, I did not think of this.

**Comment by zickgraf** [comment]
Ah, yes, that would probably be the best solution, as these are all one-liners anyway.

**Comment by mohamed-barakat** [comment]
Closed with #785
