### ISSUE TITLE
The role of `ObjectConstructor` and `MorphismConsctructor`

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#780]
Currently, `ObjectConstructor` and `MorphismConsctructor` have two different applications:

1. They are used to access different categories with a common interface, e.g. `MatrixCategory` and `CategoryOfRows` [here](https://github.com/homalg-project/Algebroids/blob/9d89c1725374bf970ea111b7c8575549786998a0/gap/Algebroids.gi#L767).
2. They are used to decouple the "external" (i.e., user visible) data structure from the "internal" data structure (the one used in the implementation) in combination with `WrapperCategory`, e.g. for `CategoryOfRowsAsAdditiveClosureOfRingAsCategory` [here](https://github.com/homalg-project/CAP_project/blob/fb0a13d8ca2a6095bf812d79ae9100be247bed44/FreydCategoriesForCAP/gap/CategoryOfRowsAsAdditiveClosureOfRingAsCategory.gi#L24).

These two applications are mutually exclusive: For the second application, the `ObjectConstructor` of `CategoryOfRowsAsAdditiveClosureOfRingAsCategory` has to be different from the `ObjectConstructor` of `CategoryOfRows`, while for the first they should be the same. But both applications can also be solved in other ways (the first one by using the "old" constructors as before, the second one by introducing new options for `WrapperCategory`).

We should decide what the role of `ObjectConstructor` and `MorphismConsctructor` should actually be. I still have to think about this, ideas and suggestions are welcome!

**Comment by mohamed-barakat** [comment]
I like the names.

**Comment by mohamed-barakat** [comment]
I forgot what the next step is.

**Comment by zickgraf** [comment]
> I forgot what the next step is.

There is no next step for you: You can continue using the existing system until I find the time to introduce the new system.

**Comment by zickgraf** [comment]
This is more complicated than expected (I also have to touch `CategoryConstructor` for this....) But independent of that there is a further question: Assume that we are in the setting of modeling the category of columns as the opposite of the category of rows. Then `modeling_to_modeled_object` would be `obj -> CategoryOfColumnsObject( cat, RankOfObject( Opposite( obj ) ) )` and `object_constructor` would be `rank -> CategoryOfColumnsObject( cat, rank )`. Note that in this way we specify `CategoryOfColumnsObject` twice. This has two disadvantages in general:
1. There are no checks that the two operations are in sync (i.e. that the output of `modeling_to_modeled_object` actually corresponds to the output of `object_constructor` for some object datum).
2. We always have to create a "helper" function like `CategoryOfColumnsObject` if we want to avoid code duplication.

Both problems could be solved by replacing `modeling_to_modeled_object` by `modeling_object_to_modeled_object_datum` which would be `obj -> RankOfObject( Opposite( obj ) )`. An output of this function would be an object datum to which we can apply `object_constructor` (which still would be the same function as above) to get an actual object.

With this, on a technical level things would become simpler while the interface would look asymmetrical on first sight (because we translate an object to an object datum). However, the modeling object is the object datum of the wrapper category, i.e. we actually translate object data to object data, which means that from this point of view things are much more consistent.

**Comment by mohamed-barakat** [comment]
I like this idea very much. Let me see how it would look like for some of our current examples.

**Comment by zickgraf** [comment]
> I like this idea very much. Let me see how it would look like for some of our current examples.

See [FreydCategoriesForCAP/gap/CategoryOfColumnsAsOppositeOfCategoryOfRows.gi](https://github.com/homalg-project/CAP_project/pull/964/files#diff-a6f9a0c513b2cbde65c73d2163504b1ac351c2d17ee0d3e1ea5e8922587a2d45) in #964. For example, the code which was previously in `object_constructor` is now split between `object_constructor` and `modeled_object_datum_from_modeling_object_getter_string`. I'm now confident that this is the correct interface but there are still a few things to sort out:
1. `modeled_object_datum_from_modeling_object_getter_string` gets the wrapper category and an object in the modeling category. This is unexpected at first but makes sense from the point of view mentioned above: the object in the modeling category should be seen as an object datum in the wrapper category. Maybe we can (again) find better names to reflect this view.
2. WrapperCategory uses `ObjectConstructor` et al. explicitly at some places. Those places must be updated to also include the explicit conversion. (That's the reason why `BasisOfExternalHom` and `Coefficients...` are broken in the PR).
3. `modeled_morphism_datum_from_modeling_morphism_getter_string` (and it's converse) should probably also get source and range as arguments, but I'm not sure which source and range (i.e. on which level).

To get the last point correct I will have to apply this to a setting where source and range actually carry information (e.g. `AdelmanCategoryAsFreydOf...`). Thus, I will probably defer this a bit until I have such an example.

**Comment by zickgraf** [comment]
I have pushed new commits to #964: One commit introduces the names suggested in my last comment. It also solves point 3. As a side effect, `IsWellDefined*` is now correct, which shows that this is indeed the correct approach.

Another commit introduces `OppositeOfCategoryOfRowsAsCategoryOfColumns`. This indeed works (as expected above) by simply swapping `object_constructor` and `tower_object_constructor` and so. However, the name is not fully correct: By construction, the object data of `OppositeOfCategoryOfRowsAsCategoryOfColumns` are integers, not objects in the category of rows (because `object_datum` and `tower_object_datum` both give integers). So the correct name would be `OppositeOfCategoryOfRowsAsCategoryOfColumnsWithIntegersAndMatricesAsDataStructures`. So all of this is very flexible now :D

**Comment by mohamed-barakat** [comment]
> We can of course replace the word "tower" by "modeling", which would be more general and better fit the existing nomenclature, but wouldn't be as easy to interpret in applications.

What about replacing `tower_*` by `modeling_tower_*`?

**Comment by mohamed-barakat** [comment]
I've tested the interface with the new `SkeletalFinSets := FiniteCoproductCocompletion( TerminalCategory( ) )` and it works exactly as expected. Thank you very much.

**Comment by zickgraf** [comment]
> What about replacing `tower_*` by `modeling_tower_*`?

Sounds good!

> I've tested the interface with the new `SkeletalFinSets := FiniteCoproductCocompletion( TerminalCategory( ) )` and it works exactly as expected. Thank you very much.

Perfect :-) With my `CoFreydCategory` experiment, I am confident that this interface also works in cases where the morphism datum does not carry enough information to determine source and range.

**Comment by zickgraf** [comment]
As discussed verbally, I want to modify the interface so `modeling_tower_object_constructor` can be passed as a function instead of a string. To do this, I have to define an operation `ModelingTowerObjectConstructor` which gets the modeling category as the first argument. But the modeling tower object constructor is not a property of the modeling category: The same modeling category could be wrapped in different ways, with different modeling tower object constructors.

There are multiple possible solutions:

1. We could introduce the restriction that the same category *instance* cannot be wrapped multiple times (e.g., one can still wrap different instances of CategoryOfRows, but one cannot wrap the same instance twice). This would mean that one should never wrap global instances (e.g. `FinSets`) or instances which are attributes (e.g. `MatrixCategory( QQ )`) but always create "fresh" instances of such categories.
2. We could pass the wrapper category as the first argument of `ModelingTowerObjectConstructor`. That would be semantically correct: we cannot talk about a "modeling tower" without talking about what category we want to model. But this would introduce the unexpected asymmetry mentioned in point 1 above again.

I'm in favor of solution 2. I think with the new names, the unexpected asymmetry is not so unexpected anymore (maybe its even expected to get a wrapper category when talking about a modeling tower). And this solution also is technically much simpler, which is usually a hint that this is the "correct" solution.

**Comment by mohamed-barakat** [comment]
Yes, I am in favor of solution 2.

**Comment by zickgraf** [comment]
Note: After an internal refactoring, the problem mentioned in my last comment is gone and `ModelingTowerObjectConstructor` could get the tower as the first argument again (instead of the wrapper category). However, for the semantical reasons mentioned above I'm still favoring passing the wrapper category.

**Comment by zickgraf** [comment]
Summary: With #964 merged, `WrapperCategory` has the necessary options for solving use case 2. in the top post while still being compatible with use case 1. The latter now is the official use case of `ObjectConstructor` et al.
