### ISSUE TITLE
Get rid of `IsList` in method record and cover the case of lists of lists of morphisms

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#801]
Possible names:

* `listlist_of_morphisms`
* `list_of_lists_of_morphisms`
* `matrix_of_morphisms`

Currently `MorphismBetweenDirectSumsWithGivenDirectSums` is excluded in `CategoryConstructor`, since the latter cannot deal with the unspecified `IsList`.

The `OppositeCategory` constructor has to be considered with care.

**Comment by zickgraf** [comment]
The reason why I have not tried to deal with `MorphismBetweenDirectSums` yet is that in all cases I know it can be efficiently derived from `UniversalMorphismFrom/IntoDirectSum`. Do you have an example where `MorphismBetweenDirectSums` can be implemented more efficiently than this derivation?

**Comment by mohamed-barakat** [comment]
I also got rid of such an obsolete occurrence here https://github.com/homalg-project/FunctorCategories/pull/75.
