### ISSUE TITLE
ColiftAlongEpimorphism in ModulePresentationsForCAP became slow as it invokes Kamal's new Colift

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#83]
In `CategoriesWithAmbientObjects` we need `ColiftAlongEpimorphism` to colift along epis from the ambient free modules on free generators.  Now this runs in Kamal's new code and causes an explosion in the number of matrix operations, their sizes, and most dramatically their entries! A simple computation which used to take a second now kills my laptop (allocating more than 10GB of memory). What we need here is a technical function `ColiftAlongEpimorphismFromFreeOnFreeGenerators` and a review of Kamal's code. Probably his suggestion today was right: The output morphism should be reduced modulo the relations of the target module.

**Comment by sebastianpos** [comment]
We can adjust the Cap-weight of the current implementation of
`Colift`.
If we set it higher than the Cap-weight of the automatically derived function
`ColiftAlongEpimorphism`
then your code should work as before. I prepared a commit for this
in my repository: 4fefdd8f244972b

**Comment by mohamed-barakat** [comment]
Thanks, it works 👍 I'll keep the issue open until we discuss about it tomorrow or whenever you have time.

**Comment by sebasguts** [comment]
@mohamed-barakat I guess this is resolved by now?

**Comment by mohamed-barakat** [comment]
Yes.
