### ISSUE TITLE
Shall I move `TerminalCategoryWithMultipleObjects` to CAP?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#912]
For this, I need to use Fabian's version of `CategoryConstructor`, which should be easy.

One advantage: We will be able to move ` CategoryConstructor/tst/TerminalCategoryMonoidal.tst` to `MonoidalCategories`.

**Comment by mohamed-barakat** [comment]
The legacy `CategoryConstructor` and the new one seem to differ in some aspects. It would be nice if we can discuss the differences and how to converge.

**Comment by zickgraf** [comment]
Fixed by #913.
