### ISSUE TITLE
StopCompilationAtPrimitivelyInstalledOperationsOfCategory enhancement

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#918]
As discussed, I would like to have an enhancement of `StopCompilationAtPrimitivelyInstalledOperationsOfCategory`:

* `StopCompilationAtPrimitivelyInstalledOperationsOfCategory`( cat, 0 ): CapJitCompiledFunction( func, cat ) returns func;
* `StopCompilationAtPrimitivelyInstalledOperationsOfCategory`( cat, n ): CapJitCompiledFunction( func, cat ) returns func resolved up to n steps and in any case stops when it hits a primitive operation before
* `StopCompilationAtPrimitivelyInstalledOperationsOfCategory`( cat ) := `StopCompilationAtPrimitivelyInstalledOperationsOfCategory`( cat, infinity )

**Comment by zickgraf** [comment]
Fixed by #923.
