### ISSUE TITLE
I suggest renaming UnderlyingCategory -> WrappedCategory in the WrapperCategory constructor

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#926]
This renaming makes it clear and easier to communicate, that the wrapper category is merely giving a semantic/interpretation to/of the wrapped one.

**Comment by mohamed-barakat** [comment]
As just mentioned, my new suggestion is `ModelingCategoy` (single `l` for American English).

**Comment by zickgraf** [comment]
Fixed by #931.
