### ISSUE TITLE
Merge CAP_INTERNAL_TERMINAL_CATEGORY and TerminalCategoryWithMultipleObjects

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#935]
Follow-up of #912:

TerminalCategoryWithMultipleObjects should become a drop-in replacement for CAP_INTERNAL_TERMINAL_CATEGORY and than be moved from MonoidalCategories to CAP.

**Comment by TKuh** [comment]
Completed via #1164 and #1167.
