### ISSUE TITLE
Compile the derivation of the homomorphism structure of MatrixCategory from the closed monoidal structure

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#939]
If we remove the homomorphism structure from MatrixCategory, it will be derived from the closed monoidal structure. However, the compiled code does not look very nice as can be seen on this branch: https://github.com/zickgraf/CAP_project/tree/MatrixCategory_hom_structure

**Comment by mohamed-barakat** [comment]
Which of the operations doesn't look good enough?

**Comment by mohamed-barakat** [comment]
Ah, yes, the interpretations:

here are some stuff is stumbled over before:

* REM_INT( number, 1 ) = 0
* QUO_INT( number, 1 ) = number

**Comment by zickgraf** [comment]
Alternatively it could be derived from `AdditiveClosure( RingAsCategory( R ) )` and then removed from `MatrixCategoryAsAdditiveClosureOfRingAsCategory` (and `CategoryOfRowsAsAdditiveClosureOfRingAsCategory`).

**Comment by zickgraf** [comment]
With #1101, `CategoryOfRows` now compiles its homomorphism structure from the homomorphism structure of `AdditiveClosure( RingAsCategory( R ) )`.
