### ISSUE TITLE
TensorProductOnMorphismsWithGivenTensorProducts in AttributeCategoryForCAP

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#96]
`TensorProductOnMorphismsWithGivenTensorProducts` appears in `ListPrimitivelyInstalledOperationsOfCategory` of categories with attributes. This is wrong:

For example in `ActionsForCAP/examples/ActionsTest.g`:
```
gap> "TensorProductOnMorphismsWithGivenTensorProducts" in ListPrimitivelyInstalledOperationsOfCategory( cat );
true
```

See, e.g., https://github.com/homalg-project/FunctorCategories/commit/98d9c4abcb8b9089dc3fc782aa34ccf37111ad0f.

**Comment by sebastianpos** [comment]
Thanks for pointing out this error in the ActionCategory.

In 37c7736b63596d6336178 I introduced a NoInstallList
for the AttributeCategory in which you can enlist
primitive functions not to be installed for the specific
category you are currently implementing.

This would also do the trick for
your FunctorCategories.

**Comment by mohamed-barakat** [comment]
I see. However, I think the path I followed here

homalg-project/FunctorCategories@98d9c4a

is simpler and more robust as it avoids all entries of MONOIDAL_CATEGORIES_METHOD_NAME_RECORD altogether.

**Comment by sebastianpos** [comment]
The point is that sometimes you can lift the monoidal structure
to the attribute category (see for example CategoriesWithAttributesTest.g
in ActionsForCAP).

A solution like homalg-project/FunctorCategories@98d9c4a wouldn't allow this
which for me is not desirable.

I think even in your context it is not desirable:
If you want to model linear group actions by functors
whose source is the delooping BG of the group,
you can lift the tensor product from vector spaces
to such a functor category.

**Comment by mohamed-barakat** [comment]
I was not accurate enough. The suggested solution just prevents automatic installation. Further down in my yet uncommitted code I check if the setup allows lifting the monoidal structure:

```
    if HasIsMonoidalCategory( D ) and IsMonoidalCategory( D ) and
       HasCounit( C ) And HasComultiplication( C ) then
        AddTensorUnit( Hom,
          ... );
        
        AddTensorProductOnObjects( Hom,
          ... );
    fi;
```

install `TensorUnit` and `TensorProductOnObjects` by hand (as you do `CategoriesWithAttributesTest.g`) and loop over the remaining MONOIDAL_CATEGORIES_METHOD_NAME_RECORD which are primitive for the range category `D`.

**Comment by mohamed-barakat** [comment]
By the way: In `CategoriesWithAttributesTest.g` it looks to me as if you are installing a different monoidal structure on k-Vect than the one on finite k-dimensional k[x]-modules.

**Comment by sebastianpos** [comment]
I don't understand your last comment.

Maybe this helps: 
I installed in CategoriesWithAttributesTests.g
the tensor product over k
and not the one over k[x]
for finite dimensional k[x]-modules.

**Comment by mohamed-barakat** [comment]
OK, then it is correct. [Somehow I had in mind that this file should demonstrate how `CategoriesWithAttributes` can be used to give an alternative realization of finite dimensional k[x]-modules with their usual monoidal structure.] The package `FunctorCategories` will provide both depending on the comultiplication of the source bialgebra (bialgebroid in general).

**Comment by sebastianpos** [comment]
What you call the "usual monoidal structure" of k[x]-modules
cannot be constructed from a comultiplication map
of the form 
k[x] -> k[x] \otimes_k k[x].
So what do you mean by "easily provide"?

**Comment by mohamed-barakat** [comment]
Yes, you are right, this monoidal structure cannot be constructed from a comultiplication of this form.

**Comment by sebastianpos** [comment]
I will resume this discussion, that still has loose ends:

1) I think that the current solution with the `NoInstallList`
in the AttributeCategory is still problematic, still we will never know
which basic operations there will be the future. So I think
I will remodel the AttributeCategory in the way that the user
has to explicitly state which functions should be lifted.
I will make a new issue for this.

2) I suggest that the automatic installation of basic operations in FunctorCategories 
should also follow this idea. For example, you automatically lift functions like
`Lift` and `Colift` from the base to the functor category which is mathematically wrong.
I will make an issue for that in FunctorCategories.

**Comment by mohamed-barakat** [comment]
I agree with both points. I suggest referring to this issue in future issues and PR for CAP and other packages.
