### ISSUE TITLE
Update all existing categories in CAP_project to use `category_as_first_argument := true`

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#973]
Set `category!.category_as_first_argument := true` right after creating the category and make sure all added functions (e.g. via `AddPreCompose`) accept the category as the first argument.

**Comment by zickgraf** [comment]
The categories which should be updated can now easily be found by grepping for `category_as_first_argument := false`.

**Comment by TKuh** [comment]
In `AttributeCategoryForCAP`, generic operations are added depending on the return type of the operation.
See for example this part:

https://github.com/homalg-project/CAP_project/blob/f369742f174d47079589f1b76e45bc222951aace/AttributeCategoryForCAP/gap/AttributeCategory.gi#L447-L454

which eventually adds this generic function as the operation:

https://github.com/homalg-project/CAP_project/blob/f369742f174d47079589f1b76e45bc222951aace/AttributeCategoryForCAP/gap/AttributeCategory.gi#L209-L223

Now, when adding the category as first argument, it is not enough to just change
`function( arg )` into `function( cat, arg )`. If `arg` contains more than one element, then the `Add*` mechanism still thinks, it has too few elements. Like here (with [these](https://github.com/TKuh/CAP_project/commit/a205d7407c0da02e00e51158b5d0416319ce4464) changes):

```gap
gap examples/example.g 

Error, In AddAdditionForMorphisms: given function 1 has 2 arguments but should have 3 at /home/tom/.gap/pkg/CAP_project/CAP/gap/InstallAdds.gi:319 called from
add_function( category, [ [ func, [  ] ] ], weight 
 ); at /home/tom/.gap/pkg/CAP_project/CAP/gap/InstallAdds.gi:175 called from
add_function( category, func, -1 
 ); at /home/tom/.gap/pkg/CAP_project/CAP/gap/InstallAdds.gi:166 called from
add_function( category_with_attributes, function_to_add 
 ); at /home/tom/.gap/pkg/CAP_project/AttributeCategoryForCAP/gap/Attr\
ibuteCategory.gi:454 called from
CAP_INTERNAL_INSTALL_ADDS_FOR_CATEGORY_WITH_ATTRIBUTES( 
 structure_record 
 ); at /home/tom/.gap/pkg/CAP_project/AttributeCategoryForCAP/gap/Attr\
ibuteCategory.gi:759 called from
<function "EnhancementWithAttributes">( <arguments> )
 called from read-eval loop at examples/example.g:132
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue

brk> UpEnv(2);
brk> function_to_add;
function( cat, arg ) ... end
brk> add_function;
<Operation "AddAdditionForMorphisms">
```

Is there an easy way around this?

**Comment by zickgraf** [comment]
> Now, when adding the category as first argument, it is not enough to just change
> `function( arg )` into `function( cat, arg )`. If `arg` contains more than one element, then the `Add*` mechanism still thinks, it has too few elements.

The error is correct: `arg` is only special (i.e. a multi-argument) when being the only argument of a function. In other cases, one must use the `...` notation, that is, `function( cat, arg... )` should to the trick.

**Comment by zickgraf** [comment]
By the way: I just looked at how many cases of `category_as_first_argument := false` remain. A significant number of those cases are in the examples `VectorSpaces....g`. Feel free to check if those are well covered by LinearAlgebraForCAP and delete them if this is the case.

**Comment by zickgraf** [comment]
Thanks for the rapid progress, @TKuh!

Grepping for "category_as_first_argument := false" yields the following remaining places:

1. `CAP_project/CAP/gap/ProductCategory.gi` Is this deliberate?
2. `CAP_project/CAP/examples/DerivationTest.g` I think we can just delete this file.
3. `CategoricalTowers/GradedCategories/gap/PositivelyZGradedCategory.gi` I think you deliberately excluded this, but I think it makes sense to include it: Yes, the code should be refactored, but the first step of the refactoring would be making the code compatible with the category as the first argument anyway :D
4. Maybe you could also have a look at https://github.com/homalg-project/QPA2, a third party project which we are using, although we try to use it less and less. If it's less than half an our work, I think it would make sense to update it, if not, we can ignore it.

**Comment by TKuh** [comment]
1. Yes, the obvious changes gave me lots of errors, so I probably have to dig deeper. See https://github.com/TKuh/CAP_project/commit/333bad936125f30a60784800eae5b6b55b78deba
2. I actually already changed it to work: https://github.com/TKuh/CAP_project/commit/a1fbfd4f6d07fa3c8b1dc67bb84d0b2c304af053, but I can also just delete it, if you prefer. :D 
3. I'm not so sure. If @mohamed-barakat agrees, then I will.
4. Already mostly finished. :)

**Comment by mohamed-barakat** [comment]
> 3. I'm not so sure. If @mohamed-barakat agrees, then I will.

I am trying to make this code obsolete. I would rather leave it untouched for safer testing against the old functioning status quo.

**Comment by zickgraf** [comment]
Completed by https://github.com/homalg-project/CAP_project/pull/1453. Thanks @TKuh!

**Comment by mohamed-barakat** [comment]
Wonderful!
